//===================================================================
// COPYRIGHT  2020/09/16
//===================================================================
// ProcessPlanningService.cpp
// Header definition of class ProcessPlanningService
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/09/16 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByProcessPlanningService_H
#define ExportedByProcessPlanningService_H
#if defined(__ProcessPlanningService)
# define ExportedByProcessPlanningService   DSYExport
#else // __ProcessPlanningService
# define ExportedByProcessPlanningService   DSYImport
#endif  // __ProcessPlanningService
#include "DSYExport.h"
#endif //ExportedByProcessPlanningService_H

