// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module CM_MBOM
#======================================================================
#  2020/09/02 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0FM  JS0GROUP \
						CATDialogEngine \
						DI0PANV2  \
						CATAfrFoundation \
						CATPLMComponentInterfaces \
						CATVisItf \
						CUS_UtilFunc \
						DELPPRSystemItf \
						KnowledgeItf \
						CATCfgUseItf \
						DELPPRProcessItf \
						PLMDictionaryNavServices \
						CATPLMIdentificationAccess \
						CATPLMIntegrationAccess \
						CATPLMIntegrationUse  \
						CATPLMCfgUXItf  \
						CATObjectModelerBase \
						CatXmlItfBase \
						CatXmlItfExt \
						CATProductStructureUseItf \
						CATProductStructureInterfaces \
						CATMecModLiveUseItf			  \
						CATMecModUseItf				  \
						 JS0GROUP CATSysTS \
						 CAT3DPhysicalRepItf \
						 CATObjectModelerBase \
						 KnowledgeItf \
						 CATMecModUseItf \
						 CATInteractiveInterfaces \
						 CATPLMComponentInterfaces \
						 CATPLMIntegrationAccess \
						 PLMPSISessionInterfaces \
						 CATProductStructureInterfaces \
						 CATPLMIdentificationAccess \
						 ObjectModelerSystem \ 
						 DataCommonProtocolUse   \
#						 ExportedByMecModPubIDL	\
#						 CATMmrAutomationInterfaces  \
#						 CATMmrAutomationInterfacesRscCNext\
						 MecModProIDL MecModProIDL  \
#						 MecModTypeLib  \
						 CAAUtilityMdl \
						 DELPPRAuthFoundationItf \
						 CATMathematics  \
						 AttributeUtilities  \
						 DELWkiExposeUseItf \


# END WIZARD EDITION ZONE
