//===================================================================
// COPYRIGHT  2020/09/16
//===================================================================
// CM_CUSMBOMAddin.cpp
// Header definition of class CM_CUSMBOMAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/09/16 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CM_CUSMBOMAddin_H
#define CM_CUSMBOMAddin_H

#include "CATBaseUnknown.h"

#include "CATCreateWorkshop.h"
#include "CATAfrCommandHeader.h"

#include "CATIAfrGeneralWksAddin.h"
//-----------------------------------------------------------------------

class CM_CUSMBOMAddin: public CATBaseUnknown
{
	CATDeclareClass;
public:
// Standard constructors and destructors
// -------------------------------------
CM_CUSMBOMAddin ();
virtual ~CM_CUSMBOMAddin ();

//
// TODO: Add your methods for this class here.
void CreateCommands();
CATCmdContainer *CreateToolbars();
//

private:
// Copy constructor and equal operator
// -----------------------------------
CM_CUSMBOMAddin (CM_CUSMBOMAddin &);
CM_CUSMBOMAddin& operator=(CM_CUSMBOMAddin&);

};

//-----------------------------------------------------------------------

#endif
