//===================================================================
// COPYRIGHT DS 2021/11/30
//===================================================================
// COMACCommonMdl.cpp
// Header definition of class COMACCommonMdl
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/11/30 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByCOMACCommonMdl_H
#define ExportedByCOMACCommonMdl_H
#if defined(__COMACCommonMdl)
# define ExportedByCOMACCommonMdl   DSYExport
#else // __COMACCommonMdl
# define ExportedByCOMACCommonMdl   DSYImport
#endif  // __COMACCommonMdl
#include "DSYExport.h"
#endif //ExportedByCOMACCommonMdl_H

