M_CATMecModLiveUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMecModLiveUseItf\CATMecModLiveUseItf.m" CATMecModLiveUseItf - - - - - -
TRANSITIVEBUILT=NO
MKMK_DEVSTAGE=
MOD_LinkWith=M_JS0FM M_JS0GROUP M_JS0BASEILB M_CATSysMultiThreading M_CATSysTS M_CATSysTSObjectModeler M_CATDialogEngine M_DI0PANV2 M_CATAfrFoundation M_CATAfrItf M_CATVisItf M_CATAfrCompanion M_CATAfrComponentsModel M_CATOmx M_CATPLMIdentificationAccess M_CATPLMComponentInterfaces M_DELPPRSystemItf M_DELWkiExposeUseItf M_AttributeUtilities M_KnowledgeItf M_CATCfgUseItf M_DELPPRProcessItf M_PLMDictionaryNavServices M_CATPLMIntegrationAccess M_CATPLMIntegrationUse M_CATPLMCfgUXItf M_CATObjectModelerBase M_ObjectModelerSystem M_CATProviderItf M_CatXmlItfBase M_CatXmlItfExt M_CATProductStructureUseItf M_CATProductStructureInterfaces M_CATMecModLiveUseItf M_CATMecModUseItf M_CAT3DPhysicalRepItf M_CATInteractiveInterfaces M_PLMPSISessionInterfaces M_DataCommonProtocolUse M_CATMmrAutomationInterfaces M_DELPPRAuthFoundationItf M_CATMathematics M_SceneGraphManager M_PLMSetupDataInterfaces M_PLMLibraryNavUseItf
MKMK_WARNING=
MKMK_ZIPJAVASOURCE=
M_PLMPSISessionInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMSessionInterfaces\PLMPSISessionInterfaces.m" PLMPSISessionInterfaces - - - - - -
GProtected=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\ProtectedGenerated\win_b64
IProtected=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\ProtectedInterfaces
M_CATProductStructureUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ProductStructureUseItf\CATProductStructureUseItf.m" CATProductStructureUseItf - - - - - -
M_CATVisItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\VisualizationInterfaces\CATVisItf.m" CATVisItf - - - - - -
MKMK_BSCMAKE=
M_CATSysTSObjectModeler=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTSObjectModeler.m" CATSysTSObjectModeler - - - - - -
M_CATDialogEngine=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DialogEngine\CATDialogEngine.m" CATDialogEngine - - - - - -
M_AttributeUtilities=mkSharedLibrary "C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m" AttributeUtilities - - - - - -
GLocal=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\DelmiaUtilities.m\LocalGenerated\win_b64
ILocal=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\DelmiaUtilities.m\LocalInterfaces
M_JS0BASEILB=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\JS0BASEILB.m" JS0BASEILB - - - - - -
IPublic=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\PublicInterfaces
GPublic=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\PublicGenerated\win_b64
M_PLMDictionaryNavServices=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMDictionaryNavServices\PLMDictionaryNavServices.m" PLMDictionaryNavServices - - - - - -
M_CATOmx=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerCollection\CATOmx.m" CATOmx - - - - - -
MODSOURCES=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\DelmiaUtilities.m
MOD_INCPATH="C:\Works\DS\COMAC_DEL2\.\DelmiaTool\DelmiaUtilities.m\src" "C:\Works\DS\COMAC_DEL2\.\DelmiaTool\DelmiaUtilities.m\LocalInterfaces" "C:\Works\DS\COMAC_DEL2\.\DelmiaTool\DelmiaUtilities.m\LocalGenerated\win_b64"
M_KnowledgeItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\KnowledgeInterfaces\KnowledgeItf.m" KnowledgeItf - - - - - -
M_CATMathematics=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\Mathematics\CATMathematics.m" CATMathematics - - - - - -
GPrivate=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\PrivateGenerated\win_b64
IPrivate=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\PrivateInterfaces
USE_PDB_FILE=YES
WSPATH=C:\Works\DS\COMAC_DEL2\.
M_CATMecModUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMecModUseItf\CATMecModUseItf.m" CATMecModUseItf - - - - - -
M_CATObjectModelerBase=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerBase\CATObjectModelerBase.m" CATObjectModelerBase - - - - - -
MODPATH=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\DelmiaUtilities.m
FWNAME=DelmiaTool
WSROOT=C:\Works\DS\COMAC_DEL2\.
CONTNAME=DelmiaUtilities
M_DELPPRProcessItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRProcessItf\DELPPRProcessItf.m" DELPPRProcessItf - - - - - -
M_CatXmlItfBase=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\XMLParserItf\CatXmlItfBase.m" CatXmlItfBase - - - - - -
M_PLMSetupDataInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMSetupDataInterfaces\PLMSetupDataInterfaces.m" PLMSetupDataInterfaces - - - - - -
WSSOURCES=C:\Works\DS\COMAC_DEL2\.
M_DelmiaUtilities=mkSharedLibrary "C:\Works\DS\COMAC_DEL2\.\DelmiaTool\DelmiaUtilities.m" DelmiaUtilities - - - - - -
M_CATAfrComponentsModel=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrComponentsModel\CATAfrComponentsModel.m" CATAfrComponentsModel - - - - - -
TARGETS_VALID=cppgrammar typelibgrammar compilation sourceruler cpponly link1st link2nd runtimedata buildtimedata
M_CATProductStructureInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ProductStructureInterfaces\CATProductStructureInterfaces.m" CATProductStructureInterfaces - - - - - -
M_PLMLibraryNavUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMLibraryNavUseItf\PLMLibraryNavUseItf.m" PLMLibraryNavUseItf - - - - - -
WSENAME_msg=DelmiaTool\DelmiaUtilities.m
MODDIRNAME=DelmiaUtilities.m
M_CATAfrCompanion=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrCompanion.m" CATAfrCompanion - - - - - -
M_CATAfrFoundation=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrFoundation.m" CATAfrFoundation - - - - - -
M_JS0GROUP=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0GROUP.m" JS0GROUP - - - - - -
M_CATProviderItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DataCommonProtocolUse\CATProviderItf.m" CATProviderItf - - - - - -
NAME=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\DelmiaUtilities.m\Objects\win_b64\.mkdata.mkb
M_CATAfrItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrInterfaces\CATAfrItf.m" CATAfrItf - - - - - -
STEPS_TO_BUILD=DoxGrammar1st buildtimedata compilation cppgrammar cpponly cscimplement cscimplementclang grammar1st link1st link2nd runtimedata sourceruler typelibgrammar
WSEKEY=M_DelmiaUtilities
TARGET_DYNLINK=link1st link2nd
_MK_CLR_BLDCONF=MANAGED_CLR$(_MK_MSNET_VERS)
WIZARD_LINK_MODULES=JS0FM JS0GROUP CATDialogEngine DI0PANV2 CATAfrFoundation CATPLMComponentInterfaces CATVisItf DELPPRSystemItf DELWkiExposeUseItf AttributeUtilities KnowledgeItf CATCfgUseItf DELPPRProcessItf PLMDictionaryNavServices CATPLMIdentificationAccess CATPLMIntegrationAccess CATPLMIntegrationUse CATPLMCfgUXItf CATObjectModelerBase CatXmlItfBase CatXmlItfExt CATProductStructureUseItf CATProductStructureInterfaces CATMecModLiveUseItf CATMecModUseItf JS0GROUP CATSysTS CAT3DPhysicalRepItf CATObjectModelerBase KnowledgeItf CATMecModUseItf CATInteractiveInterfaces CATPLMComponentInterfaces CATPLMIntegrationAccess PLMPSISessionInterfaces CATProductStructureInterfaces CATPLMIdentificationAccess ObjectModelerSystem DataCommonProtocolUse CATMmrAutomationInterfaces CATMmrAutomationInterfacesRscCNext MecModProIDL MecModProIDL MecModTypeLib DELPPRAuthFoundationItf CATMathematics CATAfrFoundation CATVisItf SceneGraphManager ObjectModelerSystem CATPLMIntegrationUse PLMDictionaryNavServices CATPLMIdentificationAccess DI0PANV2 JS0FM KnowledgeItf CATObjectModelerBase CATPLMComponentInterfaces CATPLMIntegrationAccess PLMSetupDataInterfaces PLMLibraryNavUseItf CATCfgUseItf CATPLMCfgUXItf CatXmlItfBase CatXmlItfExt JS0GROUP CATSysTS CAT3DPhysicalRepItf CATMecModLiveUseItf CATObjectModelerBase KnowledgeItf CATMecModUseItf CATInteractiveInterfaces CATPLMComponentInterfaces CATPLMIntegrationAccess PLMPSISessionInterfaces CATProductStructureInterfaces CATPLMIdentificationAccess ObjectModelerSystem
WSSOURCES_Concat="C:\Works\DS\COMAC_DEL2\." "C:\Program Files\Dassault Systemes\B422\."
M_CATCfgUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMConfigUseItf\CATCfgUseItf.m" CATCfgUseItf - - - - - -
M_DI0PANV2=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\Dialog\DI0PANV2.m" DI0PANV2 - - - - - -
F_DelmiaTool=mkFrameworkCode "C:\Works\DS\COMAC_DEL2\.\DelmiaTool" DelmiaTool - -
FW_AllPreq=AdvancedMathematics,21ED2051;AfrFoundation,21EC1151;AfrInterfaces,21ED1151;AttributeTools,11EE1151;BSFBuildtimeData,21DD1140;CAT3DPhysicalRepInterfaces,21EE1151;CATGSMUseItf,21EE2051;CATGraphicProperties,21EE2051;CATIAApplicationFrame,21EE2051;CATMathStream,21ED2051;CATMecModLiveUseItf,21EE1151;CATMecModUIUseItf,21EE2051;CATMecModUseItf,21EE1151;CATMmrAutomationInterfaces,21EE1151;CATPLMComponentInterfaces,21EE1151;CATPLMConfigUXItf,21EE1151;CATPLMConfigUseItf,21EE1151;CATPLMIdentificationAccess,21EC1151;CATPLMIntegrationAccess,21EE1151;CATPLMIntegrationUse,21EE1151;CATSketcherUseItf,21EE2051;DELPPRAuthFoundationInterfaces,21EE1131;DELPPRProcessItf,21EE1151;DELPPRSystemItf,21EE1151;DELWkiExposeUseItf,21EE1151;DataCommonProtocolUse,21ED2051;Dialog,21EC1151;DialogEngine,21ED1151;GMModelInterfaces,21ED2051;GMOperatorsInterfaces,21EE2051;GeometricObjects,21ED2051;InteractiveInterfaces,21ED1151;KnowledgeInterfaces,21EC1151;Mathematics,21ED2051;ObjectModelerBase,21ED0051;ObjectModelerNavigator,21ED2051;ObjectModelerSystem,21ED1151;PLMDictionaryNavServices,21ED1151;PLMDocumentInterfaces,21EE1131;PLMLibraryNavUseItf,21EE1151;PLMSessionInterfaces,21EE2051;PLMSetupDataInterfaces,21EE1151;PLMWorkspaceInterfaces,21EE1131;ProductStructureInterfaces,21EE1151;ProductStructureUseItf,21EE1151;SGInfra,21EC2051;SGManager,21EC1151;SpecialAPI,21ED1151;System,21ED1151;SystemTS,21EC2051;VisualizationCommands,21EE2051;VisualizationController,21ED2051;VisualizationCore,21EC2051;VisualizationInterfaces,21ED1151;XMLParserItf,21ED1151;AfrComponentsModel,20CC1141;AfrNavigator,20CC1131;AutomationInterfaces,20EE1151;CATFunctionalModelerUseItf,20EE1151;CATImmVPMInterfaces,20DD1141;CATImmVPMLegacyInterfaces,20DD1151;CATImmVPMNavInterfaces,20DD1151;CATLogicalModelerUseItf,20EE1151;CATMecModExtendItf,20EE1151;CATPLMIntegrationAccessItf,20DD1151;CATPLMIntegrationInterfaces,20DD1151;CATPLMUIInterfaces,20EE1151;CATSketcherIDLItf,20EE1151;CATSkt2DGeomIntegUseItf,20EE1151;CATStyleProcessor,20DD1141;CATView,20DD1151;CATVirtualVaultSystem,20DD1151;CATWeightEquivalentUseItf,20EE1151;CM_UnitityService,10EE1131;DELPPRLiveProcessInterfaces,20EE1151;DELPPRResourceItf,20EE1151;DELPofMfgUseItf,20EE1151;ECMAScriptEngine,20DD1141;ElecHarnessItf,20EE1151;ElecIXFInterfaces,20DD1151;ElecLogicalItf,20EE1151;ElecRoutingItf,20EE1151;ElectricalInterfaces,20EE1151;Graph,20DD1151;IVInterfaces,20DD1151;InfInterfaces,20DD1151;InfInterfacesTLB,20EE1151;InfOSIDLItf,20DD1151;IntrospectionInfrastructure,20CC1141;KnowledgeIDLItf,20EE1151;MeasureGeometryInterfaces,20EE1151;MultimediaInterfaces,20DD1151;MultimediaPixelImage,20DD1151;OOCInterfaces,20CC1141;ObjectModelerCollection,20DD1131;ObjectModelerEngines,20CC1151;ObjectModelerInterfaces,20DD1151;PLMBusinessLogicInterfaces,20DD1151;PLMDictionaryInterfaces,20DD1151;PLMFolderInterfaces,20EE1151;PLMInterferenceUseItf,20EE1151;PLMManagementInterfaces,20DD1151;PLMManagementServices,20DD1151;PLMManagementServicesUI,20DD1151;PLMModelerBaseInterfaces,20DD1151;ProductStructureAccess,20EE1151;SGCoreUtils,20CC1141;UIVCoreTools,20DD1131;VIAImmersiveViewInterfaces,20DD1151;VIAMPFoundation,20DD1151;VPMEditorInterfaces,20EE1151;VisuImmersiveDialog,20CC1151;VisuImmersiveDialogEx,20DD1151;VisuImmersiveUI,20DD1151;VisualizationFoundation,20CC1151;VisualizationSceneGraph,20CC1151;
FWCOMPANYNAME=
M_CATPLMIntegrationUse=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationUse\CATPLMIntegrationUse.m" CATPLMIntegrationUse - - - - - -
BUILD=YES
MOD_Container=DelmiaUtilities.m
WS_Concat="C:\Works\DS\COMAC_DEL2\." "C:\Program Files\Dassault Systemes\B422\."
FWmkHLpath=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\IdentityCard\Objects\win_b64\.mkHLpath.mk
MOD_ObjectsPath=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\DelmiaUtilities.m\Objects\win_b64
M_ObjectModelerSystem=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerSystem\ObjectModelerSystem.m" ObjectModelerSystem - - - - - -
RTViewDataListPath=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\various\win_b64\DelmiaUtilities.m\module.data
M_CATInteractiveInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\InteractiveInterfaces\CATInteractiveInterfaces.m" CATInteractiveInterfaces - - - - - -
M_JS0FM=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0FM.m" JS0FM - - - - - -
FWCOPYRIGHT=
M_CATPLMComponentInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMComponentInterfaces\CATPLMComponentInterfaces.m" CATPLMComponentInterfaces - - - - - -
TYPELATE=mkSharedLibrary
BUILT_OBJECT_TYPE=SHARED LIBRARY
M_SceneGraphManager=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SGManager\SceneGraphManager.m" SceneGraphManager - - - - - -
IMAKEKEY_VALID=COMDYN_MODULE INCLUDED_MODULES
TARGETS_MANDATORY=cscimplement cscimplementclang
FW_INCPATH="C:\Works\DS\COMAC_DEL2\.\DelmiaTool\PrivateInterfaces" "C:\Works\DS\COMAC_DEL2\.\DelmiaTool\PrivateGenerated\win_b64" "C:\Works\DS\COMAC_DEL2\.\DelmiaTool\ProtectedInterfaces" "C:\Works\DS\COMAC_DEL2\.\DelmiaTool\ProtectedGenerated\win_b64" "C:\Works\DS\COMAC_DEL2\.\DelmiaTool\PublicInterfaces" "C:\Works\DS\COMAC_DEL2\.\DelmiaTool\PublicGenerated\win_b64"
MOD_SrcPath=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\DelmiaUtilities.m\src
DOC_RTViewDataListPath=C:\Works\DS\COMAC_DEL2\.\DelmiaTool\various\win_b64.doc\DelmiaUtilities.m\module.data
LINK_WITH=JS0FM JS0GROUP CATDialogEngine DI0PANV2 CATAfrFoundation CATPLMComponentInterfaces CATVisItf DELPPRSystemItf DELWkiExposeUseItf AttributeUtilities KnowledgeItf CATCfgUseItf DELPPRProcessItf PLMDictionaryNavServices CATPLMIdentificationAccess CATPLMIntegrationAccess CATPLMIntegrationUse CATPLMCfgUXItf CATObjectModelerBase CatXmlItfBase CatXmlItfExt CATProductStructureUseItf CATProductStructureInterfaces CATMecModLiveUseItf CATMecModUseItf JS0GROUP CATSysTS CAT3DPhysicalRepItf CATObjectModelerBase KnowledgeItf CATMecModUseItf CATInteractiveInterfaces CATPLMComponentInterfaces CATPLMIntegrationAccess PLMPSISessionInterfaces CATProductStructureInterfaces CATPLMIdentificationAccess ObjectModelerSystem DataCommonProtocolUse CATMmrAutomationInterfaces CATMmrAutomationInterfacesRscCNext MecModProIDL MecModProIDL MecModTypeLib DELPPRAuthFoundationItf CATMathematics CATAfrFoundation CATVisItf SceneGraphManager ObjectModelerSystem CATPLMIntegrationUse PLMDictionaryNavServices CATPLMIdentificationAccess DI0PANV2 JS0FM KnowledgeItf CATObjectModelerBase CATPLMComponentInterfaces CATPLMIntegrationAccess PLMSetupDataInterfaces PLMLibraryNavUseItf CATCfgUseItf CATPLMCfgUXItf CatXmlItfBase CatXmlItfExt JS0GROUP CATSysTS CAT3DPhysicalRepItf CATMecModLiveUseItf CATObjectModelerBase KnowledgeItf CATMecModUseItf CATInteractiveInterfaces CATPLMComponentInterfaces CATPLMIntegrationAccess PLMPSISessionInterfaces CATProductStructureInterfaces CATPLMIdentificationAccess ObjectModelerSystem
MOD_Included=M_DelmiaUtilities
M_DELPPRAuthFoundationItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRAuthFoundationInterfaces\DELPPRAuthFoundationItf.m" DELPPRAuthFoundationItf - - - - - -
M_CatXmlItfExt=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\XMLParserItf\CatXmlItfExt.m" CatXmlItfExt - - - - - -
M_CAT3DPhysicalRepItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CAT3DPhysicalRepInterfaces\CAT3DPhysicalRepItf.m" CAT3DPhysicalRepItf - - - - - -
M_CATPLMIdentificationAccess=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIdentificationAccess\CATPLMIdentificationAccess.m" CATPLMIdentificationAccess - - - - - -
M_CATSysTS=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTS.m" CATSysTS - - - - - -
FWPATH=C:\Works\DS\COMAC_DEL2\.\DelmiaTool
MK_BUILD_CONFIGURATION=
M_CATMmrAutomationInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMmrAutomationInterfaces\CATMmrAutomationInterfaces.m" CATMmrAutomationInterfaces - - - - - -
MKMK_DEBUG=YES
M_CATPLMIntegrationAccess=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationAccess\CATPLMIntegrationAccess.m" CATPLMIntegrationAccess - - - - - -
M_CATPLMCfgUXItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMConfigUXItf\CATPLMCfgUXItf.m" CATPLMCfgUXItf - - - - - -
M_DELWkiExposeUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELWkiExposeUseItf\DELWkiExposeUseItf.m" DELWkiExposeUseItf - - - - - -
FWSOURCES=C:\Works\DS\COMAC_DEL2\.\DelmiaTool
STEPS_TO_CLEAN=
M_CATSysMultiThreading=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysMultiThreading.m" CATSysMultiThreading - - - - - -
M_DELPPRSystemItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRSystemItf\DELPPRSystemItf.m" DELPPRSystemItf - - - - - -
MKMK_DEBUGEDITANDCONTINUE=
FWDNAME=DelmiaTool
M_DataCommonProtocolUse=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DataCommonProtocolUse\DataCommonProtocolUse.m" DataCommonProtocolUse - - - - - -
MODNAME=DelmiaUtilities
REAL_LINK_WITH=JS0FM JS0GROUP JS0BASEILB CATSysMultiThreading CATSysTS CATSysTSObjectModeler CATDialogEngine DI0PANV2 CATAfrFoundation CATAfrItf CATVisItf CATAfrCompanion CATAfrComponentsModel CATOmx CATPLMIdentificationAccess CATPLMComponentInterfaces DELPPRSystemItf DELWkiExposeUseItf AttributeUtilities KnowledgeItf CATCfgUseItf DELPPRProcessItf PLMDictionaryNavServices CATPLMIntegrationAccess CATPLMIntegrationUse CATPLMCfgUXItf CATObjectModelerBase ObjectModelerSystem CATProviderItf CatXmlItfBase CatXmlItfExt CATProductStructureUseItf CATProductStructureInterfaces CATMecModLiveUseItf CATMecModUseItf CAT3DPhysicalRepItf CATInteractiveInterfaces PLMPSISessionInterfaces DataCommonProtocolUse CATMmrAutomationInterfaces DELPPRAuthFoundationItf CATMathematics SceneGraphManager PLMSetupDataInterfaces PLMLibraryNavUseItf
