//===================================================================
// COPYRIGHT  2020/09/16
//===================================================================
// CMCreateZWSystemCmd.cpp
// Header definition of class CMCreateZWSystemCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/09/16 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CMCreateZWSystemCmd_H
#define CMCreateZWSystemCmd_H

#include "ProcessPlanningService.h"
#include "CATStateCommand.h"
#include "CATSysBoolean.h"
#include "CATDialogAgent.h"

#include "iostream.h"

#include "CMSystemZWDlg.h"
#include "CATPathElementAgent.h"

//CATPLMComponentInterfaces 
#include "CATIPLMNavReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavRepInstance.h"

#include "PPRUtity.h"

//VisualizationInterfaces 
#include "CATPathElement.h"
#include "CATListPtrCATIAdpPLMIdentificator.h"
#include "CATListPtrCATIPLMNavReference.h"
//-----------------------------------------------------------------------

class CMCreateZWSystemCmd : public CATStateCommand
{
	DeclareResource(CMCreateZWSystemCmd, CATStateCommand)

public:
	// Standard constructors and destructors
	// -------------------------------------
	CMCreateZWSystemCmd();
	virtual ~CMCreateZWSystemCmd();

	//
	// TODO: Add your methods for this class here.
	virtual void     BuildGraph();

	/**
	* Action associated to state transitions.
	*/
	virtual CATBoolean  ActionOne(void * data);

	virtual CATBoolean OKAction(void *data);

	virtual CATBoolean ApplyAction(void *data);

	virtual CATBoolean CancelAction(void *data);

	CATBoolean CheckInputCode(int code);

	CATBoolean CheckZWSelect();

	CATBoolean ElementSelection(void * data);

	void FilterSelectObject();

	HRESULT CreateDELZWSystem();

	CATUnicodeString sApplyZWCode;
	//

private:
	// Copy constructor and equal operator
	// -----------------------------------
	CMCreateZWSystemCmd(CMCreateZWSystemCmd &);
	CMCreateZWSystemCmd& operator=(CMCreateZWSystemCmd&);

	CATBoolean Init(void *data);

	PPRUtity spPPRUtity;

	CMSystemZWDlg *_Panel;

	CATDialogAgent *_OKAgent;
	CATDialogAgent *_ApplyAgent;
	CATDialogAgent *_CloseAgent;
	CATDialogAgent *_CancleAgent;

	CATPathElementAgent *_pSelectAgent;

	CATBaseUnknown        * _pSelectedElement;
	CATIPLMNavRepInstance * _pSelectedRepInstance;
	CATIPLMNavOccurrence  * _pSelectedOccurrence;
	CATIPLMNavReference   * _pSelectedReference;

	CATUnicodeString sInputZWExternalID;

	CATUnicodeString sGWCodeId;

	CATUnicodeString sInputZWName;

	CATUnicodeString sInputEffecivity;

	CATIPLMNavReference * pMIDComponentRef;
	CATIPLMNavInstance * pMIDCompInstance;
	CATIPLMNavOccurrence * pMIDComponentOcc;
	CATIPLMNavReference * pMIDFatherCompRef;

	CATIPLMNavReference * pZWFatherRef;
	CATIPLMNavOccurrence * pZWFatherOcc;

	CATIPLMNavReference * pZWPreviousRef;
	CATIPLMNavOccurrence * pZWPreviousOcc;

};

//-----------------------------------------------------------------------

#endif

