//===================================================================
// COPYRIGHT  2020/09/27
//===================================================================
// CMCreateMakePartCmd.cpp
// Header definition of class CMCreateMakePartCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/09/27 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CMCreateMakePartCmd_H
#define CMCreateMakePartCmd_H

#include "ProcessPlanningService.h"
#include "CATStateCommand.h"

#include "CMMakePartDlg.h"
#include "CATPathElementAgent.h"

//CATPLMComponentInterfaces 
#include "CATIPLMNavReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavInstance.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavReference.h"
#include "CATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavEntity.h"

// CAT3DPhysicalRepInterfaces Framework
#include "CATIPsiRepresentationLoadMode.h"

#include "CATSysBoolean.h"
#include "CATDialogAgent.h"

//VisualizationInterfaces 
#include "CATPathElement.h"



#include "iostream.h"
#include "CATListPtrCATIAdpPLMIdentificator.h"
#include "CATListPtrCATIPLMNavReference.h"

// 添加包
// ObjectModelerBase Framework
#include "CATOmbLifeCycleRootsBag.h"

// KnowledgeInterfaces Framework
#include "CATITypeDictionary.h"
//CATPLMIntegrationAccess
#include "CATAdpAttributeSet.h"

//MecModInterfaces Framework
#include "CATIMmiPrtContainer.h"
#include "CATIMmiMechanicalFeature.h"


//CATPLMIdentificationAccess Framework
#include "CATPLMCoreType.h"

//ObjectSpecsModeler Framework
#include "CATIPartRequest.h"

// CATPLMComponentInterfaces Framework
#include "CATIPLMNavInstance.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavReference.h"
#include "CATIPLMNavRepReference.h"
#include "CATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavEntity.h"

// CAT3DPhysicalRepInterfaces Framework
#include "CATIPsiRepresentationLoadMode.h"

// System Framework
#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"

// others
#include "iostream.h"
//MecModInterfaces Framework
#include "CATIPartRequest.h"

#include "CATIMmiUseBodyContent.h"
#include "CATIAlias.h"      // to retrieve a specific body 

#include "CATLISTV_CATBaseUnknown.h" 
#include "CATIMmiUsePrtPart.h" 


//System Framewrks
#include "CATBoolean.h"
#include "CATUnicodeString.h"
#include "iostream.h"

//-----------------------------------------------------------------------

#define _RETURN_IF_FAILED_(hr, message) \
	if (FAILED(hr)) \
		{ cout << "=== FAILED ===> " << message << endl; return 1; } else	{	cout << "=== OK ===> " << message << endl; }

#define _RETURN_IF_TRUE_(ret, message) \
	if (ret) \
		{ cout << "=== FAILED ===> " << message << endl; return ret; } else	{	cout << "=== OK ===> " << message << endl; }



class CMCreateMakePartCmd: public CATStateCommand
{
	DeclareResource(CMCreateMakePartCmd, CATStateCommand)
public:
// Standard constructors and destructors
// -------------------------------------
CMCreateMakePartCmd ();
virtual ~CMCreateMakePartCmd ();

//
// TODO: Add your methods for this class here.
virtual CATBoolean  ActionOne(void * data);

virtual CATBoolean OKAction(void *data);

virtual CATBoolean ApplyAction(void *data);

virtual CATBoolean CancelAction(void *data);

CATBoolean ElementSelection(void * data);

void BuildGraph();

HRESULT CrateManufacturingPart();


// ******************** 几个包 *********************
// DELIPPRProcessOutputAuth::SetProcessOutput()  from edu CAAFmiProcessOutput.cpp		//RunUseCase
int SetResultingProduct(CATBaseUnknown * ipNewProdRef);

int FindReference( CATOmbLifeCycleRootsBag & iLifeCycleBag,
					const CATAdpAttributeSet & iAttributeSet,
					CATIType * ipModelerType,
					const IID & iIID,
					void ** oppReference);

void ReleasePtr(CATBaseUnknown * piCBU);

HRESULT GetOccurrenceFromProcessReference( const CATIPLMNavReference_var & ihNavRef, CATIPLMNavOccurrence_var & ohNavOcc);

CATUnicodeString GetAliasName(CATBaseUnknown * ipBaseUnknown);

//  选择性粘贴 fengy 2021.11.22
HRESULT CMCreateMakePartCmd::SpecificalCopy(CATBaseUnknown_var ispOriObject,
											CATIMmiMechanicalFeature_var ispTargetObject,
											CATIMmiMechanicalFeature_var & ospResult,
											CATBoolean iMode=true);

// 自行添加 module 一直 KO! 没办法 只能添加在函数内部！
HRESULT CAAMmrGetPartFromProduct(CATIPLMNavInstance_var   spNavInstance, CATIPartRequest_var  & ospPartFromProduct);

HRESULT CAAMmrGetGeometry(CATIPartRequest_var ispModelPart, const CATUnicodeString iInputName,
	CATBaseUnknown ** oInput);


// 解决 BU toRef fengy 2021.11.18
CATIPLMNavReference_var  FromBUToRef(CATBaseUnknown * ipNewProdRef);

void DeleteFeature(CATBaseUnknown_var spObj);
void UpdateFeature(CATBaseUnknown_var spObj);


// ******************** 几个包 *********************

// 2021.11.23 fengy  没找到OOTB 的功能 右键-更改零件几何体
HRESULT ChangePartBodyandRemove(CATIMmiMechanicalFeature_var ispNew3DPart, CATIMmiMechanicalFeature_var ispResult);

// fengy  2021.11.23 从当前的partbody下获取所有的子集！含递归嵌套？
HRESULT GetAllSolidsUndCurBody(CATIMmiMechanicalFeature_var ispResult, CATLISTV(CATBaseUnknown_var) & ospSolidList);

// fengy 2021.11.17 输出CATIPLMNavReference_var  pProduct替换  car 模型！
HRESULT  CreateNew3DPartInNewProd(CATIPLMNavReference *ipProductRef, CATBaseUnknown *& opNewProdBU);

CATBoolean CheckSelectObject();

void FilterSelectObject();

CATBoolean ChangeRadioNotifyCopy(void *data);

CATBoolean ChangeRadioNotifyInput(void *data);
//

private:
// Copy constructor and equal operator
// -----------------------------------
CMCreateMakePartCmd (CMCreateMakePartCmd &);
CMCreateMakePartCmd& operator=(CMCreateMakePartCmd&);

CMMakePartDlg *_Panel;

CATUnicodeString iManuPartType;
CATUnicodeString sPartExternalId;

CATDialogAgent *_OKAgent;
CATDialogAgent *_ApplyAgent;
CATDialogAgent *_CancleAgent;
CATDialogAgent *_CloseAgent;

CATPathElementAgent *_pSelectAgent;

CATDlgRadioButton *_pRadioBtnCopy;
CATDlgRadioButton *_pRadioBtnInput;

CATBaseUnknown        * _pSelectedElement;
CATIPLMNavOccurrence  * _pSelectedOccurrence;
CATIPLMNavRepInstance * _pSelectedRepInstance;
CATIPLMNavReference   * _pSelectedReference;

CATIPLMNavReference *pProvidePartRef;
CATIPLMNavOccurrence *pProvidePartOcc;

CATIPLMNavOccurrence * pNewManuPartOcc ;		// create 空的 MA Process Occ

CATIPLMNavReference *pMARootRef;
CATIPLMNavOccurrence *pMARootOcc;

CATIPLMNavReference *pPartFatherRef;
CATIPLMNavOccurrence *pPartFatherOcc;

CATIPLMNavReference *pProductRef;				// cad
CATIPLMNavOccurrence *pProductOcc;
CATIPLMNavInstance *pProductInstance;
CATUnicodeString	 _strMAExternal_ID;

};

//-----------------------------------------------------------------------

#endif
