//===================================================================
// COPYRIGHT  2020/09/29
//===================================================================
// CMMBOMReportCmd.cpp
// Header definition of class CMMBOMReportCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/09/29 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CMMBOMReportCmd_H
#define CMMBOMReportCmd_H

#include "ProcessPlanningService.h"

#include "CATPathElementAgent.h"

//CATPLMComponentInterfaces 
#include "CATIPLMNavReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavInstance.h"
#include "CATSysBoolean.h"
#include "CATDialogAgent.h"

//VisualizationInterfaces 
#include "CATPathElement.h"

//DELPPRProcessItf 
#include "DELPPRProcessNavAccess.h"
#include "DELIPPRProcessNav.h"
#include "DELIPPRProcessAuth.h"
#include "DELPPRProcessAuthAccess.h"

#include "iostream.h"

#include "CATStateCommand.h"

#include "CATPathElementAgent.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavReference.h"

#include "CMMBOMReportDlg.h"

#include "PPRUtity.h"
//-----------------------------------------------------------------------

class CMMBOMReportCmd:public CATStateCommand
{
	DeclareResource(CMMBOMReportCmd, CATStateCommand)

public:
// Standard constructors and destructors
// -------------------------------------
CMMBOMReportCmd ();
virtual ~CMMBOMReportCmd ();

//
// TODO: Add your methods for this class here.
virtual void     BuildGraph();

virtual CATBoolean OKAction(void *data);

virtual CATBoolean CancelAction(void *data);

CATBoolean ElementSelection(void * data);

void FilterSelectObject();

void GenerateMBOMReport(CATIPLMNavReference * ispMARef);
//

private:
// Copy constructor and equal operator
// -----------------------------------
CMMBOMReportCmd (CMMBOMReportCmd &);
CMMBOMReportCmd& operator=(CMMBOMReportCmd&);

CMMBOMReportDlg * _Panel;

CATPathElementAgent *_pSelectAgent;

CATDialogAgent *_OKAgent;
//CATDialogAgent *_ApplyAgent;
CATDialogAgent *_CloseAgent;
CATDialogAgent *_CancleAgent;

CATBaseUnknown        * _pSelectedElement;
CATIPLMNavOccurrence  * _pSelectedOccurrence;
CATIPLMNavRepInstance * _pSelectedRepInstance;
CATIPLMNavReference   * _pSelectedReference;

PPRUtity spPPRUtity;

CATIPLMNavReference * pSelectMBOMRef;

CATDialogTransition * _pDialogTransition;

};

//-----------------------------------------------------------------------

#endif
