// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module CM_CUSManuEngAddin
#======================================================================
#  2020/09/16 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP \
CATAfrItf \
CATAfrFoundation \
DELPPRLiveProcessItf \
DELPPRAuthFoundationItf \
DELPPRLiveSystemUseItfCPP \
DELWkiExposeUseItf \
CATImmPPRNavInterfaces \
MachiningU5Itf \



# END WIZARD EDITION ZONE
