
//===================================================================
// COPYRIGHT DS 2021/12/06
//===================================================================
// COMACWIAddin.cpp
// Header definition of class COMACWIAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/12/06 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef COMACWIAddin_H
#define COMACWIAddin_H

#include "CATBaseUnknown.h"
class CATCmdContainer;
//-----------------------------------------------------------------------

class COMACWIAddin: public CATBaseUnknown

{
CATDeclareClass;

public:

// Standard constructors and destructors
// -------------------------------------
COMACWIAddin ();
virtual ~COMACWIAddin ();

//
// TODO: Add your methods for this class here.
//
void CreateCommands();
CATCmdContainer * CreateToolbars();


private:
// Copy constructor and equal operator
// -----------------------------------
COMACWIAddin (COMACWIAddin &);
COMACWIAddin& operator=(COMACWIAddin&);
};

//-----------------------------------------------------------------------

#endif

