// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module CAAUtilityMdl
#======================================================================
#  2021/11/30 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP CATPLMIdentificationAccess CATObjectModelerBase CATPLMIntegrationUse \
PLMDocumentInterfacesItf CATPLMIntegrationAccess PLMDictionaryNavServices \
KnowledgeItf CATAfrFoundation DI0PANV2 JS0FM CATPLMComponentInterfaces \
DELPPRSystemItf DELPPRProcessItf CATProductStructureInterfaces CATPLMUIInterfaces \
PLMSetupDataInterfaces 
# END WIZARD EDITION ZONE
