//===================================================================
// COPYRIGHT  2021/02/04
//===================================================================
// CMMBOMFastenDlg.cpp
// Header definition of class CMMBOMFastenDlg
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/02/04 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef CMMBOMFastenDlg_h
#define CMMBOMFastenDlg_h

#include "CATDlgDialog.h"
class CATDlgLabel;
class CATDlgLabel;
class CATDlgLabel;
class CATDlgEditor;
class CATDlgLabel;
class CATDlgLabel;
class CATDlgCombo;
class CATDlgEditor;
class CATDlgEditor;
class CATDlgEditor;
class CATDlgCheckButton;

// Begin of User Code
enum COMACMBOMFastenDlg_ControlID
{
	ID_SelectRModelEditor,
	ID_SelectManuAssemEditor,
	ID_FastenDetailCombo,
	ID_FastenNumberEditor,
	ID_FastenUsingEditor,
	ID_FastenPairCheckButton
};
// End of User Code

class  CMMBOMFastenDlg : public CATDlgDialog {
	DeclareResource(CMMBOMFastenDlg, CATDlgDialog)

public:
	CMMBOMFastenDlg(CATDialog * iParent, const CATString& iDialogName);

	virtual ~CMMBOMFastenDlg();
	void Build();

	// Copy ctor and assignment operators are declared but not defined by infra
	CMMBOMFastenDlg(const CMMBOMFastenDlg&);
	CMMBOMFastenDlg& operator= (const CMMBOMFastenDlg&);

private:
	CATDlgLabel* _Label1;
	CATDlgLabel* _Label2;
	CATDlgLabel* _Label3;
	CATDlgEditor* _Editor4;
	CATDlgLabel* _Label4;
	CATDlgLabel* _Label5;
	CATDlgLabel* _Label6;
	CATDlgCombo* _Combo1;
	CATDlgEditor* _Editor1;
	CATDlgEditor* _Editor2;
	CATDlgEditor* _Editor3;
	CATDlgCheckButton* _CheckButton1;

	// Begin of User Code
public:
	CATDlgEditor* GetEditor(int iCtrlID);
	CATDlgCombo* GetCombo(int iCtrlID);
	CATDlgCheckButton* GetCheckButton(int iCtrlID);
	// End of User Code

};


#endif
