M_CATMecModLiveUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMecModLiveUseItf\CATMecModLiveUseItf.m" CATMecModLiveUseItf - - - - - -
M_ProcessPlanningService=mkSharedLibrary "C:\Works\DS\COMAC_DEL2\.\CM_ManuEngServiceFrm\ProcessPlanningService.m" ProcessPlanningService - - - - - -
TRANSITIVEBUILT=NO
MKMK_DEVSTAGE=
MOD_LinkWith=M_JS0GROUP M_JS0BASEILB M_CATSysMultiThreading M_CATSysTS M_CATSysTSObjectModeler M_CATObjectModelerBase M_CATOmx M_CATProviderItf M_CATPLMIdentificationAccess M_CATPLMComponentInterfaces M_CATPLMIntegrationUse M_CATProductStructureInterfaces M_CATPLMIntegrationAccess M_KnowledgeItf M_CATVisItf M_PLMDocumentInterfacesItf M_PLMDictionaryNavServices M_ProcessPlanningService M_CATDialogEngine M_DI0PANV2 M_JS0FM M_CATAfrFoundation M_CATAfrItf M_CATAfrCompanion M_CATAfrComponentsModel M_CUS_UtilFunc M_DELPPRSystemItf M_DELPPRProcessItf M_CATProductStructureUseItf M_CATMecModLiveUseItf M_CATMecModUseItf M_CAT3DPhysicalRepItf M_DataCommonProtocolUse M_AttributeUtilities
MKMK_WARNING=
MKMK_ZIPJAVASOURCE=
GProtected=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\ProtectedGenerated\win_b64
IProtected=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\ProtectedInterfaces
M_CATProductStructureUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ProductStructureUseItf\CATProductStructureUseItf.m" CATProductStructureUseItf - - - - - -
M_CATVisItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\VisualizationInterfaces\CATVisItf.m" CATVisItf - - - - - -
MKMK_BSCMAKE=
M_CATSysTSObjectModeler=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTSObjectModeler.m" CATSysTSObjectModeler - - - - - -
M_CATDialogEngine=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DialogEngine\CATDialogEngine.m" CATDialogEngine - - - - - -
M_AttributeUtilities=mkSharedLibrary "C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m" AttributeUtilities - - - - - -
GLocal=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\COMACCAABatchNewVersion.m\LocalGenerated\win_b64
ILocal=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\COMACCAABatchNewVersion.m\LocalInterfaces
M_JS0BASEILB=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\JS0BASEILB.m" JS0BASEILB - - - - - -
IPublic=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\PublicInterfaces
GPublic=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\PublicGenerated\win_b64
M_PLMDictionaryNavServices=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMDictionaryNavServices\PLMDictionaryNavServices.m" PLMDictionaryNavServices - - - - - -
M_CATOmx=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerCollection\CATOmx.m" CATOmx - - - - - -
MODSOURCES=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\COMACCAABatchNewVersion.m
MOD_INCPATH="C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\COMACCAABatchNewVersion.m\src" "C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\COMACCAABatchNewVersion.m\LocalInterfaces" "C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\COMACCAABatchNewVersion.m\LocalGenerated\win_b64"
M_KnowledgeItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\KnowledgeInterfaces\KnowledgeItf.m" KnowledgeItf - - - - - -
GPrivate=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\PrivateGenerated\win_b64
IPrivate=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\PrivateInterfaces
USE_PDB_FILE=YES
WSPATH=C:\Works\DS\COMAC_DEL2\.
M_CATMecModUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMecModUseItf\CATMecModUseItf.m" CATMecModUseItf - - - - - -
M_CATObjectModelerBase=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerBase\CATObjectModelerBase.m" CATObjectModelerBase - - - - - -
MODPATH=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\COMACCAABatchNewVersion.m
FWNAME=CAACOMACPPRFrm
WSROOT=C:\Works\DS\COMAC_DEL2\.
CONTNAME=COMACCAABatchNewVersion
M_DELPPRProcessItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRProcessItf\DELPPRProcessItf.m" DELPPRProcessItf - - - - - -
M_COMACCAABatchNewVersion=mkLoadModule "C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\COMACCAABatchNewVersion.m" COMACCAABatchNewVersion - - - - - -
WSSOURCES=C:\Works\DS\COMAC_DEL2\.
M_CATAfrComponentsModel=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrComponentsModel\CATAfrComponentsModel.m" CATAfrComponentsModel - - - - - -
TARGETS_VALID=cppgrammar typelibgrammar compilation sourceruler cpponly link rmsmanifest runtimedata buildtimedata
M_CATProductStructureInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ProductStructureInterfaces\CATProductStructureInterfaces.m" CATProductStructureInterfaces - - - - - -
WSENAME_msg=CAACOMACPPRFrm\COMACCAABatchNewVersion.m
MODDIRNAME=COMACCAABatchNewVersion.m
M_CATAfrCompanion=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrCompanion.m" CATAfrCompanion - - - - - -
M_CATAfrFoundation=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrFoundation.m" CATAfrFoundation - - - - - -
M_JS0GROUP=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0GROUP.m" JS0GROUP - - - - - -
M_CATProviderItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DataCommonProtocolUse\CATProviderItf.m" CATProviderItf - - - - - -
NAME=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\COMACCAABatchNewVersion.m\Objects\win_b64\.mkdata.mkb
M_CATAfrItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrInterfaces\CATAfrItf.m" CATAfrItf - - - - - -
STEPS_TO_BUILD=DoxGrammar1st buildtimedata compilation cppgrammar cpponly cscimplement cscimplementclang grammar1st link rmsmanifest runtimedata sourceruler typelibgrammar
WSEKEY=M_COMACCAABatchNewVersion
_MK_CLR_BLDCONF=MANAGED_CLR$(_MK_MSNET_VERS)
WIZARD_LINK_MODULES=JS0GROUP CATSysTS CATObjectModelerBase CATPLMComponentInterfaces CATPLMIntegrationUse CATProductStructureInterfaces CATPLMIntegrationAccess CAAWSPInterfaces KnowledgeItf CATPLMIdentificationAccess CATVisItf CATMathematics PLMDocumentInterfacesItf PLMDictionaryNavServices ProcessPlanningService CATDialogEngine DI0PANV2 JS0FM CATAfrFoundation CATPLMComponentInterfaces CATVisItf CUS_UtilFunc DELPPRSystemItf KnowledgeItf CATCfgUseItf DELPPRProcessItf PLMDictionaryNavServices CATPLMIdentificationAccess CATPLMIntegrationAccess CATPLMIntegrationUse CATPLMCfgUXItf CATObjectModelerBase CatXmlItfBase CatXmlItfExt CATProductStructureUseItf CATProductStructureInterfaces CATMecModLiveUseItf CATMecModUseItf JS0GROUP CATSysTS CAT3DPhysicalRepItf CATObjectModelerBase KnowledgeItf CATMecModUseItf CATInteractiveInterfaces CATPLMComponentInterfaces CATPLMIntegrationAccess PLMPSISessionInterfaces CATProductStructureInterfaces CATPLMIdentificationAccess ObjectModelerSystem DataCommonProtocolUse AttributeUtilities
WSSOURCES_Concat="C:\Works\DS\COMAC_DEL2\." "C:\Program Files\Dassault Systemes\B422\."
M_DI0PANV2=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\Dialog\DI0PANV2.m" DI0PANV2 - - - - - -
FW_AllPreq=AfrFoundation,21EC1151;AfrProperties,21EE1151;AttributeTools,11EE1151;BSFBuildtimeData,21DD1140;CAACOMACPublicFrm,11EE1151;CAT3DPhysicalRepInterfaces,21EE1151;CATMecModLiveUseItf,21EE1151;CATMecModUseItf,21EE1151;CATPLMComponentInterfaces,21EE1151;CATPLMIdentificationAccess,21EC1151;CATPLMIntegrationAccess,21EE1151;CATPLMIntegrationUse,21EE1151;CM_ManuEngServiceFrm,11EE1151;CM_UnitityService,11EE1151;DELPPRAuthFoundationInterfaces,21EE1151;DELPPRProcessItf,21EE1151;DELPPRResourceItf,21EE1151;DELPPRSystemItf,21EE1151;DELWkiExposeUseItf,21EE1151;DataCommonProtocolUse,21ED1151;DelmiaTool,11EE1151;Dialog,21EC1151;DialogEngine,21ED1151;KnowledgeInterfaces,21EC1151;ObjectModelerBase,21ED1151;PLMDictionaryNavServices,21ED1151;PLMDocumentInterfaces,21EE1151;ProductStructureAccess,21EE1151;ProductStructureInterfaces,21EE1151;ProductStructureUseItf,21EE1151;SGManager,21EC1151;SpecialAPI,21ED1151;System,21ED1151;SystemTS,21EC1151;VisualizationInterfaces,21ED1151;AdvancedMathematics,20DD1151;AfrComponentsModel,20CC1141;AfrInterfaces,20DD1131;AfrNavigator,20EE1151;AutomationInterfaces,20EE1151;CATFunctionalModelerUseItf,20EE1151;CATGSMUseItf,20EE1151;CATImmVPMInterfaces,20DD1141;CATImmVPMLegacyInterfaces,20DD1151;CATImmVPMNavInterfaces,20DD1151;CATLogicalModelerUseItf,20EE1151;CATMathStream,20DD1151;CATMecModExtendItf,20EE1151;CATMecModUIUseItf,20EE1151;CATMmrAutomationInterfaces,20EE1151;CATPLMConfigUXItf,20EE1151;CATPLMConfigUseItf,20EE1151;CATPLMIntegrationAccessItf,20DD1151;CATPLMIntegrationInterfaces,20DD1151;CATPLMUIInterfaces,20EE1151;CATSketcherIDLItf,20EE1151;CATSketcherUseItf,20EE1151;CATSkt2DGeomIntegUseItf,20EE1151;CATStyleProcessor,20DD1141;CATView,20DD1151;CATVirtualVaultSystem,20DD1151;CATWeightEquivalentUseItf,20EE1151;DELPPRLiveProcessInterfaces,20EE1151;DELPofMfgUseItf,20EE1151;ElecHarnessItf,20EE1151;ElecIXFInterfaces,20DD1151;ElecLogicalItf,20EE1151;ElecRoutingItf,20EE1151;ElectricalInterfaces,20EE1151;GMModelInterfaces,20DD1151;GMOperatorsInterfaces,20EE1151;GeometricObjects,20DD1151;Graph,20DD1151;IVInterfaces,20DD1151;InfInterfaces,20DD1151;InfInterfacesTLB,20EE1151;InfOSIDLItf,20DD1151;InteractiveInterfaces,20DD1151;IntrospectionInfrastructure,20CC1141;KnowledgeIDLItf,20EE1151;Mathematics,20DD1131;MeasureGeometryInterfaces,20EE1151;MultimediaInterfaces,20DD1151;MultimediaPixelImage,20DD1151;OOCInterfaces,20CC1141;ObjectModelerCollection,20DD1131;ObjectModelerEngines,20CC1151;ObjectModelerInterfaces,20DD1151;ObjectModelerNavigator,20DD1151;ObjectModelerSystem,20DD1151;PLMBusinessLogicInterfaces,20DD1151;PLMDictionaryInterfaces,20DD1151;PLMFolderInterfaces,20EE1151;PLMInterferenceUseItf,20EE1151;PLMLibraryNavUseItf,20EE1151;PLMManagementInterfaces,20DD1151;PLMManagementServices,20DD1151;PLMManagementServicesUI,20DD1151;PLMModelerBaseInterfaces,20DD1151;PLMSessionInterfaces,20EE1151;PLMSetupDataInterfaces,20EE1151;PLMWorkspaceInterfaces,20EE1131;SGCoreUtils,20CC1141;SGInfra,20CC1151;UIVCoreTools,20DD1131;VIAImmersiveViewInterfaces,20DD1151;VPMEditorInterfaces,20EE1151;VisuImmersiveDialog,20CC1151;VisuImmersiveDialogEx,20DD1151;VisuImmersiveUI,20DD1151;VisualizationController,20DD1151;VisualizationCore,20CC1151;VisualizationFoundation,20CC1151;VisualizationSceneGraph,20CC1151;XMLParserItf,20DD1151;
FWCOMPANYNAME=
M_CATPLMIntegrationUse=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationUse\CATPLMIntegrationUse.m" CATPLMIntegrationUse - - - - - -
BUILD=YES
MOD_Container=COMACCAABatchNewVersion.m
M_PLMDocumentInterfacesItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMDocumentInterfaces\PLMDocumentInterfacesItf.m" PLMDocumentInterfacesItf - - - - - -
WS_Concat="C:\Works\DS\COMAC_DEL2\." "C:\Program Files\Dassault Systemes\B422\."
FWmkHLpath=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\IdentityCard\Objects\win_b64\.mkHLpath.mk
MOD_ObjectsPath=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\COMACCAABatchNewVersion.m\Objects\win_b64
RTViewDataListPath=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\various\win_b64\COMACCAABatchNewVersion.m\module.data
M_JS0FM=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0FM.m" JS0FM - - - - - -
FWCOPYRIGHT=
M_CATPLMComponentInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMComponentInterfaces\CATPLMComponentInterfaces.m" CATPLMComponentInterfaces - - - - - -
TYPELATE=mkLoadModule
BUILT_OBJECT_TYPE=LOAD MODULE
IMAKEKEY_VALID=COMDYN_MODULE
TARGETS_MANDATORY=cscimplement cscimplementclang
FW_INCPATH="C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\PrivateInterfaces" "C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\PrivateGenerated\win_b64" "C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\ProtectedInterfaces" "C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\ProtectedGenerated\win_b64" "C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\PublicInterfaces" "C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\PublicGenerated\win_b64"
MOD_SrcPath=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\COMACCAABatchNewVersion.m\src
M_CUS_UtilFunc=mkSharedLibrary "C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m" CUS_UtilFunc - - - - - -
DOC_RTViewDataListPath=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm\various\win_b64.doc\COMACCAABatchNewVersion.m\module.data
LINK_WITH=JS0GROUP CATSysTS CATObjectModelerBase CATPLMComponentInterfaces CATPLMIntegrationUse CATProductStructureInterfaces CATPLMIntegrationAccess CAAWSPInterfaces KnowledgeItf CATPLMIdentificationAccess CATVisItf CATMathematics PLMDocumentInterfacesItf PLMDictionaryNavServices ProcessPlanningService CATDialogEngine DI0PANV2 JS0FM CATAfrFoundation CATPLMComponentInterfaces CATVisItf CUS_UtilFunc DELPPRSystemItf KnowledgeItf CATCfgUseItf DELPPRProcessItf PLMDictionaryNavServices CATPLMIdentificationAccess CATPLMIntegrationAccess CATPLMIntegrationUse CATPLMCfgUXItf CATObjectModelerBase CatXmlItfBase CatXmlItfExt CATProductStructureUseItf CATProductStructureInterfaces CATMecModLiveUseItf CATMecModUseItf JS0GROUP CATSysTS CAT3DPhysicalRepItf CATObjectModelerBase KnowledgeItf CATMecModUseItf CATInteractiveInterfaces CATPLMComponentInterfaces CATPLMIntegrationAccess PLMPSISessionInterfaces CATProductStructureInterfaces CATPLMIdentificationAccess ObjectModelerSystem DataCommonProtocolUse AttributeUtilities
MOD_Included=M_COMACCAABatchNewVersion
M_CAT3DPhysicalRepItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CAT3DPhysicalRepInterfaces\CAT3DPhysicalRepItf.m" CAT3DPhysicalRepItf - - - - - -
M_CATPLMIdentificationAccess=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIdentificationAccess\CATPLMIdentificationAccess.m" CATPLMIdentificationAccess - - - - - -
M_CATSysTS=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTS.m" CATSysTS - - - - - -
FWPATH=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm
MK_BUILD_CONFIGURATION=
MKMK_DEBUG=YES
M_CATPLMIntegrationAccess=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationAccess\CATPLMIntegrationAccess.m" CATPLMIntegrationAccess - - - - - -
FWSOURCES=C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm
STEPS_TO_CLEAN=
M_CATSysMultiThreading=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysMultiThreading.m" CATSysMultiThreading - - - - - -
F_CAACOMACPPRFrm=mkFrameworkCode "C:\Works\DS\COMAC_DEL2\.\CAACOMACPPRFrm" CAACOMACPPRFrm - -
M_DELPPRSystemItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRSystemItf\DELPPRSystemItf.m" DELPPRSystemItf - - - - - -
MKMK_DEBUGEDITANDCONTINUE=
FWDNAME=CAACOMACPPRFrm
M_DataCommonProtocolUse=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DataCommonProtocolUse\DataCommonProtocolUse.m" DataCommonProtocolUse - - - - - -
MODNAME=COMACCAABatchNewVersion
REAL_LINK_WITH=JS0GROUP JS0BASEILB CATSysMultiThreading CATSysTS CATSysTSObjectModeler CATObjectModelerBase CATOmx CATProviderItf CATPLMIdentificationAccess CATPLMComponentInterfaces CATPLMIntegrationUse CATProductStructureInterfaces CATPLMIntegrationAccess KnowledgeItf CATVisItf PLMDocumentInterfacesItf PLMDictionaryNavServices ProcessPlanningService CATDialogEngine DI0PANV2 JS0FM CATAfrFoundation CATAfrItf CATAfrCompanion CATAfrComponentsModel CUS_UtilFunc DELPPRSystemItf DELPPRProcessItf CATProductStructureUseItf CATMecModLiveUseItf CATMecModUseItf CAT3DPhysicalRepItf DataCommonProtocolUse AttributeUtilities
