//===================================================================
// COPYRIGHT DS 2021/11/30
//===================================================================
// CAACOMACAddinMdl.cpp
// Header definition of class CAACOMACAddinMdl
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/11/30 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByCAACOMACAddinMdl_H
#define ExportedByCAACOMACAddinMdl_H
#if defined(__CAACOMACAddinMdl)
# define ExportedByCAACOMACAddinMdl   DSYExport
#else // __CAACOMACAddinMdl
# define ExportedByCAACOMACAddinMdl   DSYImport
#endif  // __CAACOMACAddinMdl
#include "DSYExport.h"
#endif //ExportedByCAACOMACAddinMdl_H

