//===================================================================
// COPYRIGHT Comac 2021/12/10
//===================================================================
// AttributeUtilities.cpp
// Header definition of class AttributeUtilities
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/12/10 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByAttributeUtilities_H
#define ExportedByAttributeUtilities_H
#if defined(__AttributeUtilities)
# define ExportedByAttributeUtilities   DSYExport
#else // __AttributeUtilities
# define ExportedByAttributeUtilities   DSYImport
#endif  // __AttributeUtilities
#include "DSYExport.h"
#endif //ExportedByAttributeUtilities_H

