//===================================================================
// COPYRIGHT Comac 2022/01/18
//===================================================================
// COMACCAABatchNewVersion.cpp
// Header definition of class COMACCAABatchNewVersion
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2022/01/18 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByCOMACCAABatchNewVersion_H
#define ExportedByCOMACCAABatchNewVersion_H
#if defined(__COMACCAABatchNewVersion)
# define ExportedByCOMACCAABatchNewVersion   DSYExport
#else // __COMACCAABatchNewVersion
# define ExportedByCOMACCAABatchNewVersion   DSYImport
#endif  // __COMACCAABatchNewVersion
#include "DSYExport.h"
#endif //ExportedByCOMACCAABatchNewVersion_H

