M_CATMecModLiveUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMecModLiveUseItf\CATMecModLiveUseItf.m" CATMecModLiveUseItf - - - - - -
TRANSITIVEBUILT=NO
M_CATGMModelInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\GMModelInterfaces\CATGMModelInterfaces.m" CATGMModelInterfaces - - - - - -
MKMK_DEVSTAGE=
MOD_LinkWith=M_JS0FM M_DELPPRLiveProcessItf M_CATMecModUseItf M_CATGMGeometricInterfaces M_CATMecModLiveUseItf M_CATSketcherUseItf M_CATSkt2DGeomIntegUseItf M_CATGSMUseItf M_DataCommonProtocolUse M_CATGMModelInterfaces M_JS0GROUP M_JS0BASEILB M_CATSysMultiThreading M_CATSysTS M_CATSysTSObjectModeler M_CATVisItf M_CATAfrFoundation M_CATAfrItf M_CATAfrCompanion M_CATAfrComponentsModel M_CATOmx M_CATPLMIdentificationAccess M_CATPLMComponentInterfaces M_KnowledgeItf M_DI0PANV2 M_CATObjectModelerBase M_ObjectModelerSystem M_CATProviderItf M_PLMDictionaryNavServices M_CATPLMIntegrationUse M_CATPLMIntegrationAccess M_CATDialogEngine M_CATProductStructureUseItf M_VPMEditorInterfaces M_CATProductStructureInterfaces M_CAT3DPhysicalRepItf M_CATPLMUIInterfaces M_CATPLMModelerBaseInterfaces M_CATMathematics M_CATEhiInterfaces M_CATElectricalInterfaces M_CATMecModExtendItf M_KnowledgeIDLItf M_CATInfInterfaces M_InfOSIDLItf M_CATMmrAutomationInterfaces M_CATMeasureGeometryInterfaces M_CATObjectModelerNavigator M_CATAfrNavigator M_CATMathStream M_CATGMOperatorsInterfaces M_CATGeometricObjects M_CATLogicalModelerUseItf M_CATElecLogicalItf M_CATFunctionalModelerUseItf M_PLMPSISessionInterfaces M_CATPrdAccessCAA M_CATEwrInterfaces M_CATMecModUIUseItf M_PLMFolderItf M_DELPPRProcessItf M_DELPPRResourceItf M_DELPPRSystemItf M_PLMInterferenceUseItf M_PLMSetupDataInterfaces M_CUS_UtilFunc
M_InfOSIDLItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\InfOSIDLItf\InfOSIDLItf.m" InfOSIDLItf - - - - - -
MKMK_WARNING=
MKMK_ZIPJAVASOURCE=
M_PLMPSISessionInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMSessionInterfaces\PLMPSISessionInterfaces.m" PLMPSISessionInterfaces - - - - - -
M_CATGeometricObjects=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\GeometricObjects\CATGeometricObjects.m" CATGeometricObjects - - - - - -
GProtected=C:\Works\DS\COMAC_DEL2\.\AttributeTools\ProtectedGenerated\win_b64
IProtected=C:\Works\DS\COMAC_DEL2\.\AttributeTools\ProtectedInterfaces
M_CATProductStructureUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ProductStructureUseItf\CATProductStructureUseItf.m" CATProductStructureUseItf - - - - - -
M_CATVisItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\VisualizationInterfaces\CATVisItf.m" CATVisItf - - - - - -
M_CATEwrInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ElecRoutingItf\CATEwrInterfaces.m" CATEwrInterfaces - - - - - -
MKMK_BSCMAKE=
M_CATSysTSObjectModeler=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTSObjectModeler.m" CATSysTSObjectModeler - - - - - -
M_CATDialogEngine=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DialogEngine\CATDialogEngine.m" CATDialogEngine - - - - - -
M_AttributeUtilities=mkSharedLibrary "C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m" AttributeUtilities - - - - - -
M_CATLogicalModelerUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATLogicalModelerUseItf\CATLogicalModelerUseItf.m" CATLogicalModelerUseItf - - - - - -
GLocal=C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m\LocalGenerated\win_b64
ILocal=C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m\LocalInterfaces
M_JS0BASEILB=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\JS0BASEILB.m" JS0BASEILB - - - - - -
IPublic=C:\Works\DS\COMAC_DEL2\.\AttributeTools\PublicInterfaces
GPublic=C:\Works\DS\COMAC_DEL2\.\AttributeTools\PublicGenerated\win_b64
M_PLMDictionaryNavServices=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMDictionaryNavServices\PLMDictionaryNavServices.m" PLMDictionaryNavServices - - - - - -
M_KnowledgeIDLItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\KnowledgeIDLItf\KnowledgeIDLItf.m" KnowledgeIDLItf - - - - - -
M_CATOmx=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerCollection\CATOmx.m" CATOmx - - - - - -
MODSOURCES=C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m
MOD_INCPATH="C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m\src" "C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m\LocalInterfaces" "C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m\LocalGenerated\win_b64"
M_KnowledgeItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\KnowledgeInterfaces\KnowledgeItf.m" KnowledgeItf - - - - - -
M_CATMathematics=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\Mathematics\CATMathematics.m" CATMathematics - - - - - -
GPrivate=C:\Works\DS\COMAC_DEL2\.\AttributeTools\PrivateGenerated\win_b64
IPrivate=C:\Works\DS\COMAC_DEL2\.\AttributeTools\PrivateInterfaces
USE_PDB_FILE=YES
M_CATGMOperatorsInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\GMOperatorsInterfaces\CATGMOperatorsInterfaces.m" CATGMOperatorsInterfaces - - - - - -
M_DELPPRResourceItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRResourceItf\DELPPRResourceItf.m" DELPPRResourceItf - - - - - -
WSPATH=C:\Works\DS\COMAC_DEL2\.
M_CATMecModUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMecModUseItf\CATMecModUseItf.m" CATMecModUseItf - - - - - -
M_CATAfrNavigator=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrNavigator\CATAfrNavigator.m" CATAfrNavigator - - - - - -
M_CATObjectModelerBase=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerBase\CATObjectModelerBase.m" CATObjectModelerBase - - - - - -
MODPATH=C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m
FWNAME=AttributeTools
WSROOT=C:\Works\DS\COMAC_DEL2\.
CONTNAME=AttributeUtilities
M_DELPPRProcessItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRProcessItf\DELPPRProcessItf.m" DELPPRProcessItf - - - - - -
M_PLMFolderItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMFolderInterfaces\PLMFolderItf.m" PLMFolderItf - - - - - -
M_PLMSetupDataInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMSetupDataInterfaces\PLMSetupDataInterfaces.m" PLMSetupDataInterfaces - - - - - -
WSSOURCES=C:\Works\DS\COMAC_DEL2\.
M_CATAfrComponentsModel=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrComponentsModel\CATAfrComponentsModel.m" CATAfrComponentsModel - - - - - -
TARGETS_VALID=cppgrammar typelibgrammar compilation sourceruler cpponly link1st link2nd runtimedata buildtimedata
M_CATProductStructureInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ProductStructureInterfaces\CATProductStructureInterfaces.m" CATProductStructureInterfaces - - - - - -
WSENAME_msg=AttributeTools\AttributeUtilities.m
MODDIRNAME=AttributeUtilities.m
M_CATAfrCompanion=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrCompanion.m" CATAfrCompanion - - - - - -
M_CATAfrFoundation=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrFoundation.m" CATAfrFoundation - - - - - -
M_JS0GROUP=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0GROUP.m" JS0GROUP - - - - - -
M_CATProviderItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DataCommonProtocolUse\CATProviderItf.m" CATProviderItf - - - - - -
NAME=C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m\Objects\win_b64\.mkdata.mkb
M_CATPLMUIInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMUIInterfaces\CATPLMUIInterfaces.m" CATPLMUIInterfaces - - - - - -
M_CATSkt2DGeomIntegUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATSkt2DGeomIntegUseItf\CATSkt2DGeomIntegUseItf.m" CATSkt2DGeomIntegUseItf - - - - - -
M_CATAfrItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrInterfaces\CATAfrItf.m" CATAfrItf - - - - - -
STEPS_TO_BUILD=DoxGrammar1st buildtimedata compilation cppgrammar cpponly cscimplement cscimplementclang grammar1st link1st link2nd runtimedata sourceruler typelibgrammar
WSEKEY=M_AttributeUtilities
TARGET_DYNLINK=link1st link2nd
M_CATEhiInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ElecHarnessItf\CATEhiInterfaces.m" CATEhiInterfaces - - - - - -
M_VPMEditorInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\VPMEditorInterfaces\VPMEditorInterfaces.m" VPMEditorInterfaces - - - - - -
_MK_CLR_BLDCONF=MANAGED_CLR$(_MK_MSNET_VERS)
WIZARD_LINK_MODULES=JS0FM DELPPRLiveProcessItf CATMecModUseItf CATGMGeometricInterfaces CATMecModLiveUseItf CATSketcherUseItf CATGSMUseItf DataCommonProtocolUse CATGMModelInterfaces JS0GROUP CATVisItf CATAfrFoundation CATPLMComponentInterfaces KnowledgeItf DI0PANV2 CATPLMIdentificationAccess CATObjectModelerBase PLMDictionaryNavServices CATPLMIntegrationUse CATPLMIntegrationAccess CATDialogEngine CATProductStructureUseItf VPMEditorInterfaces ObjectModelerSystem CATProductStructureInterfaces CAT3DPhysicalRepItf CATPLMUIInterfaces CATPLMModelerBaseInterfaces CATMathematics CATEhiInterfaces CATElectricalInterfaces CATMecModExtendItf KnowledgeIDLItf InfPubIDL InfOSPubIDL MecModPubIDL CATMeasureGeometryInterfaces CATObjectModelerNavigator CATAfrNavigator CATGMModelInterfaces CATMathStream CATGMOperatorsInterfaces CATGeometricObjects CATLogicalModelerUseItf CATElecLogicalItf CATFunctionalModelerUseItf PLMPSISessionInterfaces CATPrdAccessCAA CATEwrInterfaces CATMecModUIUseItf PLMFolderItf DELPPRProcessItf DELPPRResourceItf DELPPRSystemItf PLMInterferenceUseItf ComacV6ExcelPubFunc PLMSetupDataInterfaces CUS_UtilFunc
M_CATObjectModelerNavigator=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerNavigator\CATObjectModelerNavigator.m" CATObjectModelerNavigator - - - - - -
M_CATPLMModelerBaseInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMModelerBaseInterfaces\CATPLMModelerBaseInterfaces.m" CATPLMModelerBaseInterfaces - - - - - -
F_AttributeTools=mkFrameworkCode "C:\Works\DS\COMAC_DEL2\.\AttributeTools" AttributeTools - -
WSSOURCES_Concat="C:\Works\DS\COMAC_DEL2\." "C:\Program Files\Dassault Systemes\B422\."
M_DI0PANV2=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\Dialog\DI0PANV2.m" DI0PANV2 - - - - - -
FW_AllPreq=AdvancedMathematics,21ED2051;AfrFoundation,21EC1151;AfrInterfaces,21ED1151;AfrNavigator,21EC1151;AutomationInterfaces,21EE1151;BSFBuildtimeData,21DD1140;CAT3DPhysicalRepInterfaces,21EE1151;CATFunctionalModelerUseItf,21EE1151;CATGSMUseItf,21EE1151;CATGraphicProperties,21EE2051;CATIAApplicationFrame,21EE2051;CATLogicalModelerUseItf,21EE1151;CATMathStream,21ED1151;CATMecModExtendItf,21EE1151;CATMecModLiveUseItf,21EE1151;CATMecModUIUseItf,21EE1151;CATMecModUseItf,21EE1151;CATMmrAutomationInterfaces,21EE1151;CATPLMComponentInterfaces,21EE1151;CATPLMConfigUXItf,21EE1151;CATPLMConfigUseItf,21EE1151;CATPLMIdentificationAccess,21EC1151;CATPLMIntegrationAccess,21EE1151;CATPLMIntegrationUse,21EE1151;CATPLMUIInterfaces,21EE1151;CATSketcherUseItf,21EE1151;CATWeightEquivalentUseItf,21EE1151;CM_UnitityService,11EE1131;DELPPRAuthFoundationInterfaces,21EE1131;DELPPRLiveProcessInterfaces,21EE1151;DELPPRProcessItf,21EE1151;DELPPRResourceItf,21EE1151;DELPPRSystemItf,21EE1151;DELPofMfgUseItf,21EE1151;DataCommonProtocolUse,21ED1151;Dialog,21EC1151;DialogEngine,21ED1151;ElecHarnessItf,21EE1151;ElecLogicalItf,21EE1151;ElecRoutingItf,21EE1151;ElectricalInterfaces,21EE1151;GMModelInterfaces,21ED1151;GMOperatorsInterfaces,21EE1151;GeometricObjects,21ED1151;InfInterfaces,21ED1151;InfOSIDLItf,21ED1151;InteractiveInterfaces,21ED1151;KnowledgeIDLItf,21EE1151;KnowledgeInterfaces,21EC1151;Mathematics,21ED1151;MeasureGeometryInterfaces,21EE1151;ObjectModelerBase,21ED1151;ObjectModelerNavigator,21ED1151;ObjectModelerSystem,21ED1151;PLMDictionaryNavServices,21ED1151;PLMDocumentInterfaces,21EE1131;PLMFolderInterfaces,21EE1151;PLMInterferenceUseItf,21EE1151;PLMModelerBaseInterfaces,21ED1151;PLMSessionInterfaces,21EE1151;PLMSetupDataInterfaces,21EE1151;PLMWorkspaceInterfaces,21EE1131;ProductStructureAccess,21EE1151;ProductStructureInterfaces,21EE1151;ProductStructureUseItf,21EE1151;SGInfra,21EC2051;SpecialAPI,21ED1151;System,21ED1151;SystemTS,21EC1151;VPMEditorInterfaces,21EE1151;VisualizationCommands,21EE2051;VisualizationController,21ED2051;VisualizationCore,21EC2051;VisualizationInterfaces,21ED1151;XMLParserItf,21ED1151;AfrComponentsModel,20CC1141;CATImmVPMInterfaces,20DD1141;CATImmVPMLegacyInterfaces,20DD1151;CATImmVPMNavInterfaces,20DD1151;CATPLMIntegrationAccessItf,20DD1151;CATPLMIntegrationInterfaces,20DD1151;CATSketcherIDLItf,20EE1151;CATSkt2DGeomIntegUseItf,20EE1151;CATStyleProcessor,20DD1141;CATView,20DD1151;CATVirtualVaultSystem,20DD1151;ECMAScriptEngine,20DD1141;ElecIXFInterfaces,20DD1151;Graph,20DD1151;IVInterfaces,20DD1151;IntrospectionInfrastructure,20CC1141;MultimediaInterfaces,20DD1151;MultimediaPixelImage,20DD1151;OOCInterfaces,20CC1141;ObjectModelerCollection,20DD1131;ObjectModelerEngines,20CC1151;ObjectModelerInterfaces,20DD1151;PLMBusinessLogicInterfaces,20DD1151;PLMDictionaryInterfaces,20DD1151;PLMLibraryNavUseItf,20EE1151;PLMManagementInterfaces,20DD1151;PLMManagementServices,20DD1151;PLMManagementServicesUI,20DD1151;SGCoreUtils,20CC1141;SGManager,20CC1151;UIVCoreTools,20DD1131;VIAImmersiveViewInterfaces,20DD1151;VIAMPFoundation,20DD1151;VisuImmersiveDialog,20CC1151;VisuImmersiveDialogEx,20DD1151;VisuImmersiveUI,20DD1151;VisualizationFoundation,20CC1151;VisualizationSceneGraph,20CC1151;
FWCOMPANYNAME=
M_DELPPRLiveProcessItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRLiveProcessInterfaces\DELPPRLiveProcessItf.m" DELPPRLiveProcessItf - - - - - -
M_CATPLMIntegrationUse=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationUse\CATPLMIntegrationUse.m" CATPLMIntegrationUse - - - - - -
M_CATMecModUIUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMecModUIUseItf\CATMecModUIUseItf.m" CATMecModUIUseItf - - - - - -
BUILD=YES
MOD_Container=AttributeUtilities.m
WS_Concat="C:\Works\DS\COMAC_DEL2\." "C:\Program Files\Dassault Systemes\B422\."
FWmkHLpath=C:\Works\DS\COMAC_DEL2\.\AttributeTools\IdentityCard\Objects\win_b64\.mkHLpath.mk
M_CATGMGeometricInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\GeometricObjects\CATGMGeometricInterfaces.m" CATGMGeometricInterfaces - - - - - -
M_CATPrdAccessCAA=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ProductStructureAccess\CATPrdAccessCAA.m" CATPrdAccessCAA - - - - - -
MOD_ObjectsPath=C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m\Objects\win_b64
M_ObjectModelerSystem=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerSystem\ObjectModelerSystem.m" ObjectModelerSystem - - - - - -
RTViewDataListPath=C:\Works\DS\COMAC_DEL2\.\AttributeTools\various\win_b64\AttributeUtilities.m\module.data
M_JS0FM=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0FM.m" JS0FM - - - - - -
FWCOPYRIGHT=
M_CATPLMComponentInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMComponentInterfaces\CATPLMComponentInterfaces.m" CATPLMComponentInterfaces - - - - - -
TYPELATE=mkSharedLibrary
M_CATMeasureGeometryInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\MeasureGeometryInterfaces\CATMeasureGeometryInterfaces.m" CATMeasureGeometryInterfaces - - - - - -
BUILT_OBJECT_TYPE=SHARED LIBRARY
IMAKEKEY_VALID=COMDYN_MODULE INCLUDED_MODULES
TARGETS_MANDATORY=cscimplement cscimplementclang
M_PLMInterferenceUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMInterferenceUseItf\PLMInterferenceUseItf.m" PLMInterferenceUseItf - - - - - -
FW_INCPATH="C:\Works\DS\COMAC_DEL2\.\AttributeTools\PrivateInterfaces" "C:\Works\DS\COMAC_DEL2\.\AttributeTools\PrivateGenerated\win_b64" "C:\Works\DS\COMAC_DEL2\.\AttributeTools\ProtectedInterfaces" "C:\Works\DS\COMAC_DEL2\.\AttributeTools\ProtectedGenerated\win_b64" "C:\Works\DS\COMAC_DEL2\.\AttributeTools\PublicInterfaces" "C:\Works\DS\COMAC_DEL2\.\AttributeTools\PublicGenerated\win_b64"
MOD_SrcPath=C:\Works\DS\COMAC_DEL2\.\AttributeTools\AttributeUtilities.m\src
M_CUS_UtilFunc=mkSharedLibrary "C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m" CUS_UtilFunc - - - - - -
DOC_RTViewDataListPath=C:\Works\DS\COMAC_DEL2\.\AttributeTools\various\win_b64.doc\AttributeUtilities.m\module.data
LINK_WITH=JS0FM DELPPRLiveProcessItf CATMecModUseItf CATGMGeometricInterfaces CATMecModLiveUseItf CATSketcherUseItf CATGSMUseItf DataCommonProtocolUse CATGMModelInterfaces JS0GROUP CATVisItf CATAfrFoundation CATPLMComponentInterfaces KnowledgeItf DI0PANV2 CATPLMIdentificationAccess CATObjectModelerBase PLMDictionaryNavServices CATPLMIntegrationUse CATPLMIntegrationAccess CATDialogEngine CATProductStructureUseItf VPMEditorInterfaces ObjectModelerSystem CATProductStructureInterfaces CAT3DPhysicalRepItf CATPLMUIInterfaces CATPLMModelerBaseInterfaces CATMathematics CATEhiInterfaces CATElectricalInterfaces CATMecModExtendItf KnowledgeIDLItf InfPubIDL InfOSPubIDL MecModPubIDL CATMeasureGeometryInterfaces CATObjectModelerNavigator CATAfrNavigator CATGMModelInterfaces CATMathStream CATGMOperatorsInterfaces CATGeometricObjects CATLogicalModelerUseItf CATElecLogicalItf CATFunctionalModelerUseItf PLMPSISessionInterfaces CATPrdAccessCAA CATEwrInterfaces CATMecModUIUseItf PLMFolderItf DELPPRProcessItf DELPPRResourceItf DELPPRSystemItf PLMInterferenceUseItf ComacV6ExcelPubFunc PLMSetupDataInterfaces CUS_UtilFunc
MOD_Included=M_AttributeUtilities
M_CAT3DPhysicalRepItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CAT3DPhysicalRepInterfaces\CAT3DPhysicalRepItf.m" CAT3DPhysicalRepItf - - - - - -
M_CATFunctionalModelerUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATFunctionalModelerUseItf\CATFunctionalModelerUseItf.m" CATFunctionalModelerUseItf - - - - - -
M_CATPLMIdentificationAccess=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIdentificationAccess\CATPLMIdentificationAccess.m" CATPLMIdentificationAccess - - - - - -
M_CATSysTS=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTS.m" CATSysTS - - - - - -
FWPATH=C:\Works\DS\COMAC_DEL2\.\AttributeTools
MK_BUILD_CONFIGURATION=
M_CATMmrAutomationInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMmrAutomationInterfaces\CATMmrAutomationInterfaces.m" CATMmrAutomationInterfaces - - - - - -
MKMK_DEBUG=YES
M_CATMathStream=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMathStream\CATMathStream.m" CATMathStream - - - - - -
M_CATPLMIntegrationAccess=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationAccess\CATPLMIntegrationAccess.m" CATPLMIntegrationAccess - - - - - -
M_CATInfInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\InfInterfaces\CATInfInterfaces.m" CATInfInterfaces - - - - - -
M_CATGSMUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATGSMUseItf\CATGSMUseItf.m" CATGSMUseItf - - - - - -
FWSOURCES=C:\Works\DS\COMAC_DEL2\.\AttributeTools
M_CATSketcherUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATSketcherUseItf\CATSketcherUseItf.m" CATSketcherUseItf - - - - - -
STEPS_TO_CLEAN=
M_CATSysMultiThreading=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysMultiThreading.m" CATSysMultiThreading - - - - - -
M_CATElecLogicalItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ElecLogicalItf\CATElecLogicalItf.m" CATElecLogicalItf - - - - - -
M_CATElectricalInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ElectricalInterfaces\CATElectricalInterfaces.m" CATElectricalInterfaces - - - - - -
M_DELPPRSystemItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DELPPRSystemItf\DELPPRSystemItf.m" DELPPRSystemItf - - - - - -
MKMK_DEBUGEDITANDCONTINUE=
M_CATMecModExtendItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATMecModExtendItf\CATMecModExtendItf.m" CATMecModExtendItf - - - - - -
FWDNAME=AttributeTools
M_DataCommonProtocolUse=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DataCommonProtocolUse\DataCommonProtocolUse.m" DataCommonProtocolUse - - - - - -
MODNAME=AttributeUtilities
REAL_LINK_WITH=JS0FM DELPPRLiveProcessItf CATMecModUseItf CATGMGeometricInterfaces CATMecModLiveUseItf CATSketcherUseItf CATSkt2DGeomIntegUseItf CATGSMUseItf DataCommonProtocolUse CATGMModelInterfaces JS0GROUP JS0BASEILB CATSysMultiThreading CATSysTS CATSysTSObjectModeler CATVisItf CATAfrFoundation CATAfrItf CATAfrCompanion CATAfrComponentsModel CATOmx CATPLMIdentificationAccess CATPLMComponentInterfaces KnowledgeItf DI0PANV2 CATObjectModelerBase ObjectModelerSystem CATProviderItf PLMDictionaryNavServices CATPLMIntegrationUse CATPLMIntegrationAccess CATDialogEngine CATProductStructureUseItf VPMEditorInterfaces CATProductStructureInterfaces CAT3DPhysicalRepItf CATPLMUIInterfaces CATPLMModelerBaseInterfaces CATMathematics CATEhiInterfaces CATElectricalInterfaces CATMecModExtendItf KnowledgeIDLItf CATInfInterfaces InfOSIDLItf CATMmrAutomationInterfaces CATMeasureGeometryInterfaces CATObjectModelerNavigator CATAfrNavigator CATMathStream CATGMOperatorsInterfaces CATGeometricObjects CATLogicalModelerUseItf CATElecLogicalItf CATFunctionalModelerUseItf PLMPSISessionInterfaces CATPrdAccessCAA CATEwrInterfaces CATMecModUIUseItf PLMFolderItf DELPPRProcessItf DELPPRResourceItf DELPPRSystemItf PLMInterferenceUseItf PLMSetupDataInterfaces CUS_UtilFunc
