//===================================================================
// COPYRIGHT Comac 2021/12/29
//===================================================================
// COMACPLMReorderCmd.cpp
// Header definition of class COMACPLMReorderCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/12/29 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef COMACPLMReorderCmd_H
#define COMACPLMReorderCmd_H

#include "CATCommand.h"

//----------------------------------------------------------------------

/**
* Describe your command here.
* <p>
* Using this prefered syntax will enable mkdoc to document your class.
* <p>
* refer to programming resources of System framework.
* (consult base class description).
*/
class COMACPLMReorderCmd : public CATCommand
{
public:

	COMACPLMReorderCmd();
	virtual ~COMACPLMReorderCmd();

	/**
	* Overload this method: when your command gains focus
	* <p>
	* Activates a command.
	* @param iFromClient
	*   The command that requests to activate the current one.
	* @param iEvtDat
	*   The notification sent.
	*/
	virtual CATStatusChangeRC Activate(
		CATCommand * iFromClient,
		CATNotification * iEvtDat);

	/**
	*  Overload this method: when your command loses focus
	* <p>
	* Deactivates a command.
	* @param iFromClient
	*   The command that takes the current active place.
	* @param iEvtDat
	*   The notification sent.
	*/
	virtual CATStatusChangeRC Desactivate(
		CATCommand * iFromClient,
		CATNotification * iEvtDat);

	/**
	*  Overload this method: when your command is canceled
	* <p>
	* Cancels a command.
	* @param iFromClient
	*   The command that takes the current active place.
	* @param iEvtDat
	*   The notification sent.
	*/
	virtual CATStatusChangeRC Cancel(
		CATCommand * iFromClient,
		CATNotification * iEvtDat);
private:

	// 日志生成
	CATUnicodeString  logFilePath;					// 全局变量 只能在类外声明？

};

//----------------------------------------------------------------------

#endif
