//===================================================================
// COPYRIGHT  2020/09/27
//===================================================================
// ComacReNameOperationsCmd.cpp
// Header definition of class ComacReNameOperationsCmd
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/09/27 Creation: Code generated by the 3DS wizard
//===================================================================

#ifndef ComacReNameOperationsCmd_H
#define ComacReNameOperationsCmd_H

//#include "ProcessPlanningService.h"
#include "CATStateCommand.h"

#include "ComacReNameOperationsDlg.h"
#include "CATPathElementAgent.h"

//CATPLMComponentInterfaces 
#include "CATIPLMNavReference.h"
#include "CATIPLMNavOccurrence.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavInstance.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavReference.h"
#include "CATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavEntity.h"

// CAT3DPhysicalRepInterfaces Framework
#include "CATIPsiRepresentationLoadMode.h"

#include "CATSysBoolean.h"
#include "CATDialogAgent.h"

//VisualizationInterfaces 
#include "CATPathElement.h"



#include "iostream.h"
#include "CATListPtrCATIAdpPLMIdentificator.h"
#include "CATListPtrCATIPLMNavReference.h"

// 添加包
// ObjectModelerBase Framework
#include "CATOmbLifeCycleRootsBag.h"

// KnowledgeInterfaces Framework
#include "CATITypeDictionary.h"
//CATPLMIntegrationAccess
#include "CATAdpAttributeSet.h"

//MecModInterfaces Framework
#include "CATIMmiPrtContainer.h"
#include "CATIMmiMechanicalFeature.h"


//CATPLMIdentificationAccess Framework
#include "CATPLMCoreType.h"

//ObjectSpecsModeler Framework
#include "CATIPartRequest.h"

// CATPLMComponentInterfaces Framework
#include "CATIPLMNavInstance.h"
#include "CATIPLMNavRepInstance.h"
#include "CATIPLMNavReference.h"
#include "CATIPLMNavRepReference.h"
#include "CATIPLMNavEntity.h"
#include "CATListPtrCATIPLMNavEntity.h"

// CAT3DPhysicalRepInterfaces Framework
#include "CATIPsiRepresentationLoadMode.h"

// System Framework
#include "CATBaseUnknown.h"
#include "CATUnicodeString.h"

// others
#include "PPRUtity.h"

//MecModInterfaces Framework
#include "CATIPartRequest.h"

#include "CATIMmiUseBodyContent.h"
#include "CATIAlias.h"      // to retrieve a specific body 

#include "CATLISTV_CATBaseUnknown.h" 

#include "CATString.h"


//System Framewrks
#include "CATBoolean.h"
#include "CATUnicodeString.h"
#include "iostream.h"


#include "CATDlgCheckButton.h"


#define nAsciiCharA 65
#define nAsciiCharZ 90

//-----------------------------------------------------------------------

#define _RETURN_IF_FAILED_(hr, message) \
	if (FAILED(hr)) \
		{ cout << "=== FAILED ===> " << message << endl; return 1; } else	{	cout << "=== OK ===> " << message << endl; }

#define _RETURN_IF_TRUE_(ret, message) \
	if (ret) \
		{ cout << "=== FAILED ===> " << message << endl; return ret; } else	{	cout << "=== OK ===> " << message << endl; }



class ComacReNameOperationsCmd : public CATStateCommand
{
	DeclareResource(ComacReNameOperationsCmd, CATStateCommand)
public:
	// Standard constructors and destructors
	// -------------------------------------
	ComacReNameOperationsCmd();
	virtual ~ComacReNameOperationsCmd();
	void BuildGraph();

	//
	// TODO: Add your methods for this class here.
	virtual CATBoolean OKAction(void *data);

	virtual CATBoolean ApplyAction(void *data);

	virtual CATBoolean CancelAction(void *data);

	CATBoolean ElementSelection(void * data);

	void FilterSelectObject();

	//   fengy 2021.12.15  InsertFOinstruction
	HRESULT InsertFOinstruction();
	
	CATBoolean CheckSelectObject();

	// fengy 2022.1.5  ReNameOperations
	void ReNameOperations(CATIPLMNavReference *ipFO_OPFatherRef);

	// fengy 2022.1.10 从workplan 获取下面的所有OP title
	void getOPtitles(CATIPLMNavReference * ipFO_OPFatherRef);

	// fengy 2022.1.10  获取ref 的前后缀 010-A istrOPReftitle
	bool  GetOPPreAndSuffix(CATUnicodeString istrOPReftitle, int &onPreffix, int &onSuffix);

	// fengy 2022.1.10 找到当前 list下需要更改的三种类别
	HRESULT SeekIndexToMod(CATListOfInt &onList_index_ChangePre,
							CATListOfInt &onList_index_ChangePreAddSuffix,
							CATListOfInt &onList_index_ChangePreKeepSuffix);

		// fengy 2022.1.10 对当前 list下三种类别 做改名动作！
	HRESULT RunOPNameModify(CATListOfInt inList_index_ChangePre,
							CATListOfInt inList_index_ChangePreAddSuffix,
							CATListOfInt inList_index_ChangePreKeepSuffix,
							CATIPLMNavReference *ipFO_OPFatherRef);

	// fengy 2022.1.10  判断list内 与当前 index 相邻（后一个）是否相同
	bool isNextContinue(CATListOfCATUnicodeString strList, int i);

	// fengy 2022.1.10  判断list内 与当前 index 相邻（后一个）是否，   前缀数字一致&&含后缀字母 （case3）
	bool isNextSuffixCotinue(CATListOfCATUnicodeString strList, int i);

	// 1 检测出：是否 含有相同前缀，但后缀不是以A打头（不相邻！）的tmpStr —— 修改成 以A打头后缀！
	HRESULT SearchModifyCase3_1(CATListOfCATUnicodeString & iostrListOPReftitle_tmp, CATListOfCATUnicodeString & iostrListOPInsttitle_tmp);			// io 变量！

	// 2 检测出：是否 带有后缀字母，但前缀字母唯一的 cese—— 修改成 去掉后缀，保留前缀！
	HRESULT SearchModifyCase3_2(CATListOfCATUnicodeString & iostrListOPReftitle_tmp, CATListOfCATUnicodeString & iostrListOPInsttitle_tmp);			// io 变量！

	//// 0 检测出：是否 含有 相邻的前缀差值为10 ，跳过并行工序 tmpStr —— 修改成 前缀数字 差值为10！
	//HRESULT SearchModifyCase4(CATListOfCATUnicodeString & iostrListOPReftitle_tmp, CATListOfCATUnicodeString & iostrListOPInsttitle_tmp);		// io 变量！


private:
	// Copy constructor and equal operator
	// -----------------------------------
	ComacReNameOperationsCmd(ComacReNameOperationsCmd &);
	ComacReNameOperationsCmd& operator=(ComacReNameOperationsCmd&);

	PPRUtity spPPRUtity;

	ComacReNameOperationsDlg * _Panel;


	// agent
	CATDialogAgent *_OKAgent;
	CATDialogAgent *_ApplyAgent;
	CATDialogAgent *_CancleAgent;
	CATDialogAgent *_CloseAgent;

	CATPathElementAgent *_pSelectAgent;
	
	CATBaseUnknown        * _pSelectedElement;
	CATIPLMNavOccurrence  * _pSelectedOccurrence;
	CATIPLMNavRepInstance * _pSelectedRepInstance;
	CATIPLMNavReference   * _pSelectedReference;

	// ========= ComacReNameOperationsCmd ======= 
	
	CATIPLMNavReference		*pFO_OPFatherRef;
	CATIPLMNavOccurrence	*pFO_OPFatherOcc;
	
	CATListOfCATUnicodeString  _strListOPReftitle_before;						// 改名前的OP ref title
	CATListOfCATUnicodeString  _strListOPInsttitle_before;						// 改名前的OP inst title


	CATListPtrCATIPLMNavReference    _ListOPRef;
	CATListPtrCATIPLMNavInstance     _ListOPInst;
};

//-----------------------------------------------------------------------

#endif
