//===================================================================
// COPYRIGHT  2020/09/22
//===================================================================
// PPRUtity.cpp
// Header definition of class PPRUtity
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2020/09/22 Creation: Code generated by the 3DS wizard
//===================================================================

#include "PPRUtity.h"
#include "fengyHelper.h"

#include "CATInstantiateComponent.h"
#include "CATIPrdObject.h"
//-----------------------------------------------------------------------------
// PPRUtity : constructor
//-----------------------------------------------------------------------------
PPRUtity::PPRUtity()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// PPRUtity : destructor
//-----------------------------------------------------------------------------

PPRUtity::~PPRUtity()
{
//
// TODO: Place code here.
//
}


#define _RELEASE_PTR_(ptr) \
   if (NULL!=(ptr)) { (ptr)->Release(); (ptr)=NULL; }

#define _RETURN_IF_FAILED_(hr, message) \
   if (FAILED(hr)) \
        {  cout << "  == CAAWKINavAuth FAILED ==> " << message << " " << hr << endl; return hr; } \
        else \
        {  cout << "  == CAAWKINavAuth OK ==> " << message << endl; }

#define _RETURN_IF_NULL_(ptr, message) \
   if (NULL==ptr) \
        {  cout << "  == CAAWKINavAuth FAILED ==> " << message << endl; return E_FAIL; } \
        else \
        {  cout << "  == CAAWKINavAuth OK ==> " << message << " " << ptr << endl; }



HRESULT PPRUtity::CreateSubSystemOrOperation(const CATUnicodeString &iTypeName,
	CATIPLMNavReference *&iParentRef,
	CATIPLMNavInstance  *&pNavInstOp)
{
	HRESULT rc = S_FALSE;
	if(iTypeName == "")
		return E_INVALIDARG;

	CATITypeDictionary_var hTypeDic = CATGlobalFunctions::GetTypeDictionary();

	DELIPPRSystemAuth_var hPPRSystemAuth;
	rc = ::GetPPRSystemAuth(hPPRSystemAuth);

	if (NULL_var == hTypeDic || NULL_var == hPPRSystemAuth || NULL_var == iParentRef)
		return E_INVALIDARG;

	CATIType_var hGeneralSystemType = NULL_var;
	rc = hTypeDic->FindType(iTypeName, hGeneralSystemType);

	// Create Subsystem / Operation, provide parent reference and return instance
	CATIPLMNavReference * pNavRefParent = iParentRef;
	cout << "PPRUtity : SubSystem parent  " << pNavRefParent << endl;

	rc = hPPRSystemAuth->CreateSubSystemOrOperation(pNavRefParent, hGeneralSystemType, (void **)&pNavInstOp);

	return rc;
}

HRESULT PPRUtity::GetOccFromSystemFather(CATIPLMNavOccurrence *ipSystemFatherOcc,
	CATIPLMNavInstance *ipNavInstSubSys, CATIPLMNavOccurrence *&opSubSystemOcc)
{
	if (ipSystemFatherOcc == NULL || ipNavInstSubSys == NULL)
		return S_FALSE;
	CATListPtrCATIPLMNavInstance ListSubSysInst;
	DELIPPRSystemOccAuth * pPPRSystemOccAuth = NULL;
	pPPRSystemOccAuth = getDELIPPRSystemOccAuth();
	HRESULT rc = pPPRSystemOccAuth->FromOccurrenceToPathOfInstances(ipSystemFatherOcc, ListSubSysInst);
	ListSubSysInst.Append(ipNavInstSubSys);

	CATIPLMNavInstance_var spNavInstance = ListSubSysInst[1];
	CATIPLMNavReference * spRootSystemRef = NULL;
	rc = spNavInstance->GetFather(spRootSystemRef);

	if (spRootSystemRef == NULL) {
		cout << "Failed to get Root system reference" << endl;
		return S_FALSE;
	}
	CATIPLMNavOccurrence * spRootSystemNavOcc = NULL;
	rc = pPPRSystemOccAuth->GetOrCreateRootOccurrence(spRootSystemRef, spRootSystemNavOcc);

	if (spRootSystemNavOcc == NULL) {
		cout << "Failed to get Root system occurrence" << endl;
		return S_FALSE;
	}
	rc = pPPRSystemOccAuth->GetOccurrence(spRootSystemNavOcc, ListSubSysInst, opSubSystemOcc);

	if (opSubSystemOcc == NULL) {
		cout << "Failed to get operation occurrence" << endl;
		return S_FALSE;
	}
	return S_OK;
}

HRESULT PPRUtity::InsertExistSystem(CATBaseUnknown * ipFatherSystem, CATBaseUnknown * ipChildSystem, CATBaseUnknown *& opInstance)
{
	DELIPPRSystemAndOperationInstancesAuth *piInstanceAuth = NULL;
	HRESULT rc = ipFatherSystem->QueryInterface(IID_DELIPPRSystemAndOperationInstancesAuth,(void**)&piInstanceAuth);
	if (piInstanceAuth == NULL)
		return E_FAIL;

	rc = piInstanceAuth->AddInstanceFromType(ipChildSystem, opInstance);
	return rc;
}


HRESULT PPRUtity::CreateSubMAAssembly(const CATUnicodeString iTypeName,
	CATIPLMNavOccurrence *iParentOcc, CATIPLMNavReference *iRootRef,
	CATIPLMNavOccurrence *&pNavOccOp)
{

	DELIPPRProcessAuth_var hPPRProcessAuth;
	HRESULT rc = ::GetPPRProcessAuth(hPPRProcessAuth);
	if (!hPPRProcessAuth) 
		return E_FAIL;

	CATIType_var hSubType;
	CUSCAAUtilService::RetrieveType(iTypeName, hSubType);
	//rc = CATCkePLMNavPublicServices::RetrieveKnowledgeType(iTypeName, hCreateAssemblyType);
	
	CATIPLMNavReference * piNavRefProcess = NULL;
	rc = hPPRProcessAuth->CreateProcess(hSubType,(void **)&piNavRefProcess);
	if (NULL == piNavRefProcess)
		return E_FAIL;

	rc = hPPRProcessAuth->InsertPredecessor(iParentOcc, piNavRefProcess, iRootRef,(void **)&pNavOccOp);
	return rc;
}

HRESULT PPRUtity::InsertExistProcess(CATIPLMNavOccurrence *iParentOcc, CATIPLMNavReference *piNavRefProcess,
	CATIPLMNavReference *iRootRef,CATIPLMNavOccurrence *&pNavOccOp)
{
	DELIPPRProcessAuth_var hPPRProcessAuth;
	HRESULT rc = ::GetPPRProcessAuth(hPPRProcessAuth);
	if (!hPPRProcessAuth)
		return E_FAIL;

	rc = hPPRProcessAuth->InsertPredecessor(iParentOcc, piNavRefProcess, iRootRef, (void **)&pNavOccOp);
	if (FAILED(rc))
	{
		return rc;
	}
	//CATListPtrCATIPLMNavInstance olistInstance;
	//piNavRefProcess->ListInstances(olistInstance);
	//int n_instance = olistInstance.Size();

	//CATUnicodeString sInstanceIndex;
	//sInstanceIndex.BuildFromNum(n_instance +1);

	//CATUnicodeString sProcessName = CUSCAAUtilService::GetObjectAttrValue(piNavRefProcess,"PLM_ExternalID");
	//CATIPLMNavInstance *spNewInstance = NULL;
	//pNavOccOp->GetRelatedInstance(spNewInstance);
	//CUSCAAUtilService::SetObjectAttrString(spNewInstance, "PLM_ExternalID", sProcessName + "."+ sInstanceIndex);

	return rc;
}

HRESULT PPRUtity::CopyProductScope(CATIPLMNavReference *ipSourceRef, CATIPLMNavReference *iTargetRef)
{
	DELIPPRProcessNav_var hPPRProcessNav;
	HRESULT rc = ::GetPPRProcessNav(hPPRProcessNav);
	if (hPPRProcessNav == NULL_var)
		return rc;

	CATIPLMNavReference * scopeProductRef;
	rc = hPPRProcessNav->GetProductOfTheScope(ipSourceRef, (void**)&scopeProductRef);
	if (scopeProductRef == NULL)
		return rc;

	DELIPPRProcessAuth_var hPPRProcessAuth;
	rc = ::GetPPRProcessAuth(hPPRProcessAuth);
	if (hPPRProcessAuth == NULL_var)
		return rc;
	rc = hPPRProcessAuth->CreateScope(iTargetRef, scopeProductRef);

	return rc;
}

HRESULT PPRUtity::AssignProduct(CATIPLMNavOccurrence * spMBOMOcc, 
	CATIPLMNavOccurrence * spProductOcc)
{
	DELIPPRProcessAuth_var hPPRProcessAuth;
	HRESULT rc = ::GetPPRProcessAuth(hPPRProcessAuth);
	if (hPPRProcessAuth == NULL_var)
		return rc;

	rc = hPPRProcessAuth->AssignProduct(spMBOMOcc, spProductOcc);

	return rc;
}


HRESULT PPRUtity::CopyProductAssignment(CATIPLMNavOccurrence * iSourceMIDOcc, CATIPLMNavReference * iCtxProductRootRef,
	CATIPLMNavOccurrence * iTargetMIDOcc)
{
	cout << "**************CopyProductAssignment Start*************" << endl;
	DELIPPRProcessNav_var hPPRProcessNav;
	HRESULT rc = ::GetPPRProcessNav(hPPRProcessNav);
	if (hPPRProcessNav == NULL_var)
		return rc;

	CATListPtrCATIPLMNavOccurrence olistProductOcc;
	rc = hPPRProcessNav->GetListOfAssignedProducts(iTargetMIDOcc, iCtxProductRootRef, olistProductOcc);
	if (olistProductOcc.Size() > 0)
	{
		cout << "**************No need CopyProductAssignment*************" << endl;
		return rc;
	}

	
	hPPRProcessNav->GetListOfAssignedProducts(iSourceMIDOcc, iCtxProductRootRef, olistProductOcc);

	int nProduct = olistProductOcc.Size();
	cout << "**************Source Assign Product number is " << nProduct << " ***************" << endl;
	if (nProduct <= 0)
		return rc;

	DELIPPRProcessAuth_var hPPRProcessAuth;
	rc = ::GetPPRProcessAuth(hPPRProcessAuth);
	if (hPPRProcessAuth == NULL_var)
		return rc;
	for (int i = 1; i <= nProduct; i++)
	{
		rc = hPPRProcessAuth->AssignProduct(iTargetMIDOcc, olistProductOcc[i]);
	}
	
	cout << "**************CopyProductAssignment End*************" << endl;
	return rc;
}


CATListValCATBaseUnknown_var PPRUtity::getCurrentPPREditorRootRef(CATUnicodeString sPPRType)
{
	cout << "**************getCurrentPPREditorRootRef Start *************" << endl;
	CATListValCATBaseUnknown_var olistRootRef;
	
	DELIPPRUIServices_var hDELIPPRUIService;
	GetPPRUIServices(hDELIPPRUIService);
	if (hDELIPPRUIService == NULL_var)
		return olistRootRef;

	
	if (sPPRType == "PRODUCT")
	{
		DELIPPRUIServices::PPRRootType iRootType = DELIPPRUIServices::PRODUCT;
		hDELIPPRUIService->GetPPRRootsFromCurrentEditor(olistRootRef, iRootType);
		cout << "**************getCurrentPPREditorRootRef PRODUCT End *************" << endl;
	}	
	else if (sPPRType == "PROCESS")
	{
		DELIPPRUIServices::PPRRootType iRootType = DELIPPRUIServices::PROCESS;
		hDELIPPRUIService->GetPPRRootsFromCurrentEditor(olistRootRef, iRootType);
	}
	else if (sPPRType == "SYSTEM")
	{
		DELIPPRUIServices::PPRRootType iRootType = DELIPPRUIServices::SYSTEM;
		hDELIPPRUIService->GetPPRRootsFromCurrentEditor(olistRootRef, iRootType);
	}
	else if (sPPRType == "RESOURCE")
	{
		DELIPPRUIServices::PPRRootType iRootType = DELIPPRUIServices::RESOURCE;
		hDELIPPRUIService->GetPPRRootsFromCurrentEditor(olistRootRef, iRootType);
	}
		
	cout << "**************getCurrentPPREditorRootRef End *************" << endl;

	return olistRootRef;
}


HRESULT PPRUtity::CopyProcessStructureAssignment(CATIPLMNavOccurrence * spSourceProcessOcc,
	CATIPLMNavOccurrence * spTargetProcessOcc, CATIPLMNavReference * spProcessRootRef, CATIPLMNavReference * spProductRootRef)
{
	HRESULT rc = E_FAIL;

	CATListPtrCATIPLMNavOccurrence olistMIDComponentChildOcc;
	spSourceProcessOcc->ListChildren(olistMIDComponentChildOcc);
	int nChild = olistMIDComponentChildOcc.Size();
	CATIPLMNavOccurrence * spNewCompOcc = NULL;
	for (int i = 1; i <= nChild; i++) {
		CATIPLMNavReference * oMIDComponentChildRef = NULL;
		olistMIDComponentChildOcc[i]->GetRelatedReference(oMIDComponentChildRef);
		CATUnicodeString sChildType = CUSCAAUtilService::GetObjectKnowledgeType(oMIDComponentChildRef);
		//InsertExistProcess(spTargetProcessOcc, oMIDComponentChildRef, spProcessRootRef, spNewCompOcc);
		
		if (sChildType == TYPE_MBOMAssembly || sChildType == TYPE_MBOMKit)
		{
			CopyProcessStructureAssignment(olistMIDComponentChildOcc[i], spNewCompOcc, spProcessRootRef, spProductRootRef);
		}
		else
		{
			CopyProductAssignment(olistMIDComponentChildOcc[i], spProductRootRef, spNewCompOcc);
		}
		
	}

	return rc;
}

CATUnicodeString PPRUtity::NextFormatCode(CATUnicodeString iObjectType, CATUnicodeString iExternalID, CATUnicodeString iFormatChar)
{
	if (iExternalID == "")
		return "";
	//CATListOfCATUnicodeString olistExistID;
	//CUSCAAUtilService::QueryDBExistID(iObjectType, iExternalID + "*", olistExistID);

	//int n_ExistID = olistExistID.Size();

	CATUnicodeString iServicePath = "/resource/CUSDELMIARestService/CUSDELMIAMBOMRestService/QueryLastestComponentNumber";

	CATUnicodeString sServerUrl = CATMsgCatalog::BuildMessage((CATString)"CMMBOMReportDlg", (CATString)"ServerUrl");
	if (sServerUrl.IsNull())
	{
		CATUnicodeString Title = CATMsgCatalog::BuildMessage((CATString)"CMMBOMReportDlg", (CATString)"msg.Title");
		CATUnicodeString msg = CATMsgCatalog::BuildMessage((CATString)"CMMBOMReportDlg", (CATString)"msg.failedGetURL");
		CUSCAAUtilService::ErrorMessage(Title, msg);
		return "";
	}
	CATUnicodeString iWebSite = sServerUrl + iServicePath;
	CATUnicodeString iData = iObjectType + "@@" + iExternalID + "-*";

	CATString oUserId, oOrganisationId, oProjectId, oRoleId;
	CATAdpPublicSecurityServices::GetSecurityParameters("", oUserId, oOrganisationId, oProjectId, oRoleId);

	CATUnicodeString SecurityContext = "SecurityContext: ctx::" + oRoleId + "." + oOrganisationId + "." + oProjectId;

	CATUnicodeString returnString = CUSCAAUtilService::WebService(SecurityContext, iWebSite + "?object=" + iData);

	int n_ExistID = 0;
	returnString.ConvertToNum(&n_ExistID, "%d");

	CATUnicodeString sFormatCode;
	if (n_ExistID > 49)
	{
		n_ExistID -= 50;
		sFormatCode.BuildFromNum(1 + n_ExistID * 2, "%03d");
	}
	else
		sFormatCode.BuildFromNum(1 + n_ExistID * 2, "%02d");

	return iExternalID + iFormatChar + sFormatCode;
}

CATBoolean PPRUtity::CheckNumberChar(CATUnicodeString inputCode,int charNumber) {

	int nChar = inputCode.GetLengthInChar();
	if (charNumber != nChar)
		return FALSE;

	if(!CheckNum(inputCode))
		return FALSE;
	return TRUE;
}

CATBoolean PPRUtity::CheckNum(CATUnicodeString inputCode) 
{
	int nSize = inputCode.GetLengthInChar();
	const char * chTmp = inputCode.ConvertToChar();
	for (int i = 0; i < nSize; i++) {
		int numTmp = (int)chTmp[i];
		if (numTmp >= 48 && numTmp <= 57)
			continue;
		else 
			return FALSE;
	}
	return TRUE;
}

CATBoolean PPRUtity::CheckCapitalChar(CATUnicodeString inputCode)
{
	int nSize = inputCode.GetLengthInChar();
	const char * chTmp = inputCode.ConvertToChar();
	for (int i = 0; i < nSize; i++) {
		int numTmp = (int)chTmp[i];
		if (numTmp >= 65 && numTmp <= 90)
			continue;
		else
			return FALSE;
	}
	return TRUE;
}

CATBoolean PPRUtity::CheckLowercaseChar(CATUnicodeString inputCode)
{
	int nSize = inputCode.GetLengthInChar();
	const char * chTmp = inputCode.ConvertToChar();
	for (int i = 0; i < nSize; i++) {
		int numTmp = (int)chTmp[i];
		if (numTmp >= 97 && numTmp <= 122)
			continue;
		else
			return FALSE;
	}
	return TRUE;
}



CATUnicodeString PPRUtity::NextRevisionCode(CATUnicodeString iObjectRevision)    //001.1   002.1
{
	int splitIndex = iObjectRevision.SearchSubString(".",0);
	CATUnicodeString temp = iObjectRevision.SubString(0, splitIndex);
	int revisionIndex = 0;
	temp.ConvertToNum(&revisionIndex, "%d");

	temp.BuildFromNum(revisionIndex + 1, "%03d");
	CATUnicodeString nextRevision = temp + iObjectRevision.SubString(splitIndex, iObjectRevision.GetLengthInChar() - splitIndex);
	return nextRevision;
}


// fengy 2021.12.15  CreateInsertWorkInstruction
HRESULT PPRUtity::CreateInsertWorkInstruction(CATIPLMNavOccurrence_var ihParentOpOcc, int iWkiTypeID)
{
	HRESULT rc = E_FAIL;
	if (NULL_var == ihParentOpOcc)
	{
		cout << "# CreateInsertWorkInstruction 输入为空！" << endl;
		return rc;
	}

	DELIWKIInstructionAuthoring* pWKIAuthItf = NULL;
	rc = ::CATInstantiateComponent("DELWKIInstructionAuthoring", IID_DELIWKIInstructionAuthoring, (void**)&pWKIAuthItf);
	_RETURN_IF_NULL_(pWKIAuthItf, "  CATInstantiateComponent pWKIAuthItf=");
	if (!pWKIAuthItf)
	{
		// mkCheckSource does not recognise above macro that checks the NULL pointer
		return E_FAIL;
	}

	//Create WIs (Text)
	CATIPLMNavReference_var spWkiTextRef1;
	CATIPLMNavOccurrence_var spWKITextOcc1;
	// Create Text WorkInstruction under Op

	// type of wWorkInstruction
	CATITypeDictionary_var spTypeDic = CATGlobalFunctions::GetTypeDictionary();
	CATIType_var spWIType;

	switch (iWkiTypeID)
	{
	case ID_WIAlertType:
		spTypeDic->FindTypeInPackage("WkiAlertReference", "WorkInstructionTypePackage", spWIType);
		break;
	case ID_WIDataCollectType:
		spTypeDic->FindTypeInPackage("WkiDataCollectReference", "WorkInstructionTypePackage", spWIType);
		break;
	case ID_WISignOffType:
		spTypeDic->FindTypeInPackage("WkiSignOffReference", "WorkInstructionTypePackage", spWIType);
		break;
	case ID_WIInstructionType:
		spTypeDic->FindTypeInPackage("WkiInstructionReference", "WorkInstructionTypePackage", spWIType);
		break;
	default:
		break;
	}

	rc = pWKIAuthItf->CreateNewWorkInstruction(ihParentOpOcc, spWIType, spWKITextOcc1);
	_RETURN_IF_FAILED_(rc, "  CreateNewWorkInstruction(\"WkiInstructionReference\") ");
	cout << "    WIText name : " << fengyHelper::GetAliasName(spWKITextOcc1) << endl;

	////Insert WIs (Text)     ---插入第二个inst！
	//spWkiTextRef1 = GetRefFromOcc(spWKITextOcc1);
	//if (NULL_var != spWkiTextRef1)
	//{
	//	CATIPLMNavReference_var spRefWkiText2;
	//	CATIPLMNavOccurrence_var spWKITextOcc2;
	//	rc = pWKIAuthItf->InsertExistingWorkInstruction(ihParentOpOcc, spWkiTextRef1, spWKITextOcc2);
	//	//spRefWkiText2 = GetRefFromOcc(spWKITextOcc2);
	//	cout << "    Insert WIText name : " << fengyHelper::GetAliasName(spWKITextOcc2) << endl;
	//}
	//else
	//	return E_FAIL;

	return rc;
}

// from edu:	E:\00dev\dev_3DE_2020\1_edu\CAADELWkiExposeUseItf\CAADELWkiExposeUseItf.edu\CAAWKINavAuth.m\src\CAAWKINavAuth.cpp
CATIPLMNavReference_var PPRUtity::GetRefFromOcc(CATIPLMNavOccurrence_var &ihNavOcc)
{
	HRESULT rc(E_INVALIDARG);
	CATIPLMNavReference_var hRef;
	if (NULL_var != ihNavOcc)
	{
		CATIPLMNavReference *pRef = NULL;
		rc = ihNavOcc->GetRelatedReference(pRef);
		hRef = pRef;
		if (pRef)
		{
			pRef->Release();
			pRef = NULL;
		}
	}
	return hRef;
}

// fengy 2021.12.15  System rootref - rootOcc
HRESULT PPRUtity::GetRootOccFromSystemReference(const CATIPLMNavReference_var ispRootSystemRef, CATIPLMNavOccurrence_var & ospRootSysOcc)
{
	HRESULT rc = E_FAIL;
	if (ispRootSystemRef == NULL_var)
	{
		cout << "# PPRUtity::GetRootOccFromSystemReference 输入为空！" << endl;
		return rc;
	}
	DELIPPRSystemOccAuth* pSystemAuthService = getDELIPPRSystemOccAuth();
	DELIPPRSystemOccAuth_var hSystemOccAuth(pSystemAuthService);
	_RELEASE_PTR_(pSystemAuthService);
	if (hSystemOccAuth == NULL_var) return E_FAIL;

	CATIPLMNavOccurrence * pRootSysOcc = NULL;
	rc = hSystemOccAuth->GetOrCreateRootOccurrence(ispRootSystemRef, pRootSysOcc);
	ospRootSysOcc = pRootSysOcc;
	_RELEASE_PTR_(pRootSysOcc);
	return rc;
}

// fengy 2021.12.15 获取当前窗口下的 Root节点 enum Type
//PRODUCTProduct PPR root  PROCESSProcess PPR root  SYSTEMSystem PPR root  RESOURCEResource PPR root
HRESULT PPRUtity::GetPPRRootRefNodeFromCurrentEditor(int iType, CATIPLMNavReference_var & ospRootRef)
{
	HRESULT rc = E_FAIL;
	// 遍历找到 当前窗口下的MA 根root！
	DELIPPRUIServices* piPPRUIServices = NULL;
	::CATInstantiateComponent("DELPPRUIServices", IID_DELIPPRUIServices, (void **)&piPPRUIServices);
	if (NULL == piPPRUIServices)
	{
		fengyHelper::Notify("不能启动 DELIPPRUIServices ！");
		return rc;
	}

	CATListValCATBaseUnknown_var iospRoots;
	DELIPPRUIServices::PPRRootType iRootType;
	switch (iType)
	{
	case 1:
		iRootType = 1;
		break;
	case 2:
		iRootType = 2;
		break;
	case 3:
		iRootType = 3;
		break;
	case 4:
		iRootType = 4;
		break;
	default:
		break;
	}
	rc = piPPRUIServices->GetPPRRootsFromCurrentEditor(iospRoots, iRootType);
	int sizeofNodeRoots = iospRoots.Size();

	cout << endl;
	cout << "# sizeofNodeRoots: " << sizeofNodeRoots << endl;

	if (FAILED(rc) || (sizeofNodeRoots == 0))
	{
		fengyHelper::Notify("当前窗口不含有 Product/Process/System/Resource 根节点！");
		return rc;
	}
	if (sizeofNodeRoots > 1)
	{
		fengyHelper::Notify("当前窗口含有" + fengyHelper::IntToStr(sizeofNodeRoots) + " 个 Product/Process/System/Resource 根节点！");
		return E_FAIL;
	}

	rc = iospRoots[1]->QueryInterface(IID_CATIPLMNavReference, (void **)&ospRootRef);

	//ospRootRef = FromBUToRef(iospRoots[1]);

	cout << "PPRRootType:: 1- PRODUCT 2- PROCESS 3- SYSTEM 4- RESOURCE" << endl;
	if (FAILED(rc) || NULL_var == ospRootRef)
	{
		cout << "==== FAILED  ==== >> 获取 type:" << iType << "  ! " << endl;
		return rc;
	}
	cout << "==== OK ==== >> 获取 type:" << iType << "  ; ref alias: " << fengyHelper::GetAliasName(ospRootRef) << endl;
	return rc;
}

//// fengy 2021.1.16  CreateInstructionUnderOperation ——比较烦
//HRESULT PPRUtity::CreateInstructionUnderOperation(TYPE_FO_OP,
//	pFO_OPFatherRef, spNewFO_OPInstance)
//{
//
//}

void PPRUtity::ReleasePtr(CATBaseUnknown * piCBU)
{
	if (NULL != piCBU)
	{
		piCBU->Release();
		piCBU = NULL;
	}
}
// 解决 BU toRef fengy 2021.11.18
CATIPLMNavReference_var  PPRUtity::FromBUToRef(CATBaseUnknown * ipNewProdBU)			// BU 转到 ref，ko？
{
	CATIPLMNavReference_var ospNavRef;

	// 法一  貌似不推荐
	CATIPrdObject_var spPrdObject = ipNewProdBU;
	ReleasePtr(ipNewProdBU);

	if (NULL_var != spPrdObject)
	{
		CATIPLMNavReference* pNavRef = NULL;
		HRESULT rc = spPrdObject->GetReferenceObject((CATBaseUnknown*&)pNavRef, IID_CATIPLMNavReference);
		if (/*SUCCEEDED(rc) && */   NULL != pNavRef)
		{
			cout << "    # FromBUToRef 1111111111" << endl;
			ospNavRef = pNavRef;
			if (NULL_var != ospNavRef)
				cout << "    # FromBUToRef OK！" << endl;
			else
				cout << "    # FromBUToRef KO 3！" << endl;
		}
		else
			cout << "    # FromBUToRef KO1！" << endl;
	}
	else
		cout << "    # FromBUToRef KO2！" << endl;

	//// 法二
	//CATIPLMNavOccurrence *pNavOccOnSelObj = NULL;
	//HRESULT rc = ipNewProdBU->QueryInterface(IID_CATIPLMNavOccurrence, (void**)&pNavOccOnSelObj);

	//if (SUCCEEDED(rc))
	//{
	//	CATIPLMNavReference * pRef = NULL;
	//	pNavOccOnSelObj->GetRelatedReference(pRef);
	//	if (NULL != pRef)
	//	{
	//		ospNavRef = pRef;
	//		if (NULL_var != ospNavRef)
	//			cout << " GetRelatedReference OK! " << endl;
	//		else
	//			cout << "    # FromBUToRef KO 3！" << endl;
	//	}
	//	else
	//		cout << "    # FromBUToRef KO 1！" << endl;
	//}
	//else
	//	cout << "    # FromBUToRef KO 2！" << endl;

	return ospNavRef;
}
