// COPYRIGHT DASSAULT SYSTEMES 2009
#======================================================================
# Imakefile for module CUS_UtilFunc
#======================================================================
#  2020/09/18 Creation: Code generated by the 3DS wizard
#======================================================================
#

BUILT_OBJECT_TYPE=SHARED LIBRARY

#INSERTION ZONE NOT FOUND, MOVE AND APPEND THIS VARIABLE IN YOUR LINK STATEMENT
LINK_WITH = $(WIZARD_LINK_MODULES)
# DO NOT EDIT :: 3DS WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES =  \
JS0GROUP \
CATAfrFoundation \
CATVisItf	\
SceneGraphManager \
ObjectModelerSystem \
CATPLMIntegrationUse \
PLMDictionaryNavServices \
CATPLMIdentificationAccess \
DI0PANV2 \
JS0FM \
KnowledgeItf \
CATObjectModelerBase \
CATPLMComponentInterfaces \
CATPLMIntegrationAccess \
PLMSetupDataInterfaces \
PLMLibraryNavUseItf   \
CATCfgUseItf \
CATPLMCfgUXItf \
CatXmlItfBase \
CatXmlItfExt \

JS0GROUP CATSysTS \
CAT3DPhysicalRepItf \
CATMecModLiveUseItf \
CATObjectModelerBase \
KnowledgeItf \
CATMecModUseItf \
CATInteractiveInterfaces \
CATPLMComponentInterfaces \
CATPLMIntegrationAccess \
PLMPSISessionInterfaces \
CATProductStructureInterfaces \
CATPLMIdentificationAccess \
ObjectModelerSystem \ 




# END WIZARD EDITION ZONE
