TRANSITIVEBUILT=NO
MKMK_DEVSTAGE=
MOD_LinkWith=M_JS0GROUP M_JS0BASEILB M_CATSysMultiThreading M_CATSysTS M_CATSysTSObjectModeler M_CATAfrFoundation M_CATAfrItf M_CATVisItf M_CATAfrCompanion M_CATAfrComponentsModel M_SceneGraphManager M_CATOmx M_ObjectModelerSystem M_CATPLMIntegrationUse M_PLMDictionaryNavServices M_CATPLMIdentificationAccess M_DI0PANV2 M_JS0FM M_KnowledgeItf M_CATObjectModelerBase M_CATProviderItf M_CATPLMComponentInterfaces M_CATPLMIntegrationAccess M_PLMSetupDataInterfaces M_PLMLibraryNavUseItf M_CATCfgUseItf M_CATPLMCfgUXItf M_CatXmlItfBase M_CatXmlItfExt
MKMK_WARNING=
MKMK_ZIPJAVASOURCE=
GProtected=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\ProtectedGenerated\win_b64
IProtected=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\ProtectedInterfaces
M_CATVisItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\VisualizationInterfaces\CATVisItf.m" CATVisItf - - - - - -
MKMK_BSCMAKE=
M_CATSysTSObjectModeler=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTSObjectModeler.m" CATSysTSObjectModeler - - - - - -
GLocal=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m\LocalGenerated\win_b64
ILocal=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m\LocalInterfaces
M_JS0BASEILB=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\JS0BASEILB.m" JS0BASEILB - - - - - -
IPublic=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\PublicInterfaces
GPublic=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\PublicGenerated\win_b64
M_PLMDictionaryNavServices=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMDictionaryNavServices\PLMDictionaryNavServices.m" PLMDictionaryNavServices - - - - - -
M_CATOmx=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerCollection\CATOmx.m" CATOmx - - - - - -
MODSOURCES=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m
MOD_INCPATH="C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m\src" "C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m\LocalInterfaces" "C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m\LocalGenerated\win_b64"
M_KnowledgeItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\KnowledgeInterfaces\KnowledgeItf.m" KnowledgeItf - - - - - -
GPrivate=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\PrivateGenerated\win_b64
IPrivate=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\PrivateInterfaces
USE_PDB_FILE=YES
WSPATH=C:\Works\DS\COMAC_DEL2\.
M_CATObjectModelerBase=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerBase\CATObjectModelerBase.m" CATObjectModelerBase - - - - - -
MODPATH=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m
FWNAME=CM_UnitityService
WSROOT=C:\Works\DS\COMAC_DEL2\.
CONTNAME=CUS_UtilFunc
M_CatXmlItfBase=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\XMLParserItf\CatXmlItfBase.m" CatXmlItfBase - - - - - -
M_PLMSetupDataInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMSetupDataInterfaces\PLMSetupDataInterfaces.m" PLMSetupDataInterfaces - - - - - -
WSSOURCES=C:\Works\DS\COMAC_DEL2\.
M_CATAfrComponentsModel=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrComponentsModel\CATAfrComponentsModel.m" CATAfrComponentsModel - - - - - -
TARGETS_VALID=cppgrammar typelibgrammar compilation sourceruler cpponly link1st link2nd runtimedata buildtimedata
M_PLMLibraryNavUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\PLMLibraryNavUseItf\PLMLibraryNavUseItf.m" PLMLibraryNavUseItf - - - - - -
WSENAME_msg=CM_UnitityService\CUS_UtilFunc.m
MODDIRNAME=CUS_UtilFunc.m
M_CATAfrCompanion=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrCompanion.m" CATAfrCompanion - - - - - -
M_CATAfrFoundation=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrFoundation\CATAfrFoundation.m" CATAfrFoundation - - - - - -
M_JS0GROUP=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0GROUP.m" JS0GROUP - - - - - -
M_CATProviderItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\DataCommonProtocolUse\CATProviderItf.m" CATProviderItf - - - - - -
NAME=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m\Objects\win_b64\.mkdata.mkb
M_CATAfrItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\AfrInterfaces\CATAfrItf.m" CATAfrItf - - - - - -
STEPS_TO_BUILD=DoxGrammar1st buildtimedata compilation cppgrammar cpponly cscimplement cscimplementclang grammar1st link1st link2nd runtimedata sourceruler typelibgrammar
WSEKEY=M_CUS_UtilFunc
TARGET_DYNLINK=link1st link2nd
_MK_CLR_BLDCONF=MANAGED_CLR$(_MK_MSNET_VERS)
WIZARD_LINK_MODULES=JS0GROUP CATAfrFoundation CATVisItf SceneGraphManager ObjectModelerSystem CATPLMIntegrationUse PLMDictionaryNavServices CATPLMIdentificationAccess DI0PANV2 JS0FM KnowledgeItf CATObjectModelerBase CATPLMComponentInterfaces CATPLMIntegrationAccess PLMSetupDataInterfaces PLMLibraryNavUseItf CATCfgUseItf CATPLMCfgUXItf CatXmlItfBase CatXmlItfExt
WSSOURCES_Concat="C:\Works\DS\COMAC_DEL2\." "C:\Program Files\Dassault Systemes\B422\."
M_CATCfgUseItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMConfigUseItf\CATCfgUseItf.m" CATCfgUseItf - - - - - -
M_DI0PANV2=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\Dialog\DI0PANV2.m" DI0PANV2 - - - - - -
FW_AllPreq=AdvancedMathematics,21ED2051;AfrFoundation,21EC1151;AfrInterfaces,21ED1151;BSFBuildtimeData,21DD1140;CAT3DPhysicalRepInterfaces,21EE2051;CATGraphicProperties,21EE2051;CATIAApplicationFrame,21EE2051;CATMecModLiveUseItf,21EE2051;CATMecModUIUseItf,21EE2051;CATMecModUseItf,21EE2051;CATPLMComponentInterfaces,21EE1151;CATPLMConfigUXItf,21EE1151;CATPLMConfigUseItf,21EE1151;CATPLMIdentificationAccess,21EC1151;CATPLMIntegrationAccess,21EE1151;CATPLMIntegrationUse,21EE1151;Dialog,21EC1151;GMModelInterfaces,21ED2051;GMOperatorsInterfaces,21EE2051;KnowledgeInterfaces,21EC1151;ObjectModelerBase,21ED1151;ObjectModelerSystem,21ED1151;PLMDictionaryNavServices,21EE1151;PLMLibraryNavUseItf,21EE1151;PLMSessionInterfaces,21EE2051;PLMSetupDataInterfaces,21EE1151;ProductStructureInterfaces,21EE2051;ProductStructureUseItf,21EE2051;SGManager,21EC1151;SpecialAPI,21ED1151;System,21ED1151;VisualizationInterfaces,21ED1151;XMLParserItf,21ED1151;AfrComponentsModel,20CC1141;AfrNavigator,20CC1131;CATMathStream,20DD1151;CATPLMIntegrationAccessItf,20DD1151;CATStyleProcessor,20DD1141;CATView,20DD1151;CATVirtualVaultSystem,20DD1151;DataCommonProtocolUse,20DD2031;DialogEngine,20DD1151;ECMAScriptEngine,20DD1141;GeometricObjects,20DD1151;Graph,20DD1151;IVInterfaces,20DD1151;InfInterfaces,20DD1151;InfOSIDLItf,20DD1151;InteractiveInterfaces,20DD1151;IntrospectionInfrastructure,20CC1141;Mathematics,20DD1131;MultimediaInterfaces,20DD1151;MultimediaPixelImage,20DD1151;OOCInterfaces,20CC1141;ObjectModelerCollection,20DD1131;ObjectModelerEngines,20CC1151;ObjectModelerInterfaces,20DD1151;ObjectModelerNavigator,20DD1151;PLMDictionaryInterfaces,20DD1151;PLMModelerBaseInterfaces,20DD1151;SGCoreUtils,20CC1141;SGInfra,20CC1151;SystemTS,20CC1131;UIVCoreTools,20DD1131;VIAMPFoundation,20DD1151;VisuImmersiveDialog,20CC1151;VisuImmersiveDialogEx,20DD1151;VisuImmersiveUI,20DD1151;VisualizationController,20DD1151;VisualizationCore,20CC1151;VisualizationFoundation,20CC1151;VisualizationSceneGraph,20CC1151;
FWCOMPANYNAME=
M_CATPLMIntegrationUse=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationUse\CATPLMIntegrationUse.m" CATPLMIntegrationUse - - - - - -
BUILD=YES
MOD_Container=CUS_UtilFunc.m
WS_Concat="C:\Works\DS\COMAC_DEL2\." "C:\Program Files\Dassault Systemes\B422\."
FWmkHLpath=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\IdentityCard\Objects\win_b64\.mkHLpath.mk
MOD_ObjectsPath=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m\Objects\win_b64
M_ObjectModelerSystem=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\ObjectModelerSystem\ObjectModelerSystem.m" ObjectModelerSystem - - - - - -
F_CM_UnitityService=mkFrameworkCode "C:\Works\DS\COMAC_DEL2\.\CM_UnitityService" CM_UnitityService - -
RTViewDataListPath=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\various\win_b64\CUS_UtilFunc.m\module.data
M_JS0FM=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\System\JS0FM.m" JS0FM - - - - - -
FWCOPYRIGHT=
M_CATPLMComponentInterfaces=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMComponentInterfaces\CATPLMComponentInterfaces.m" CATPLMComponentInterfaces - - - - - -
TYPELATE=mkSharedLibrary
BUILT_OBJECT_TYPE=SHARED LIBRARY
M_SceneGraphManager=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SGManager\SceneGraphManager.m" SceneGraphManager - - - - - -
IMAKEKEY_VALID=COMDYN_MODULE INCLUDED_MODULES
TARGETS_MANDATORY=cscimplement cscimplementclang
FW_INCPATH="C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\PrivateInterfaces" "C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\PrivateGenerated\win_b64" "C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\ProtectedInterfaces" "C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\ProtectedGenerated\win_b64" "C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\PublicInterfaces" "C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\PublicGenerated\win_b64"
MOD_SrcPath=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m\src
M_CUS_UtilFunc=mkSharedLibrary "C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\CUS_UtilFunc.m" CUS_UtilFunc - - - - - -
DOC_RTViewDataListPath=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService\various\win_b64.doc\CUS_UtilFunc.m\module.data
LINK_WITH=JS0GROUP CATAfrFoundation CATVisItf SceneGraphManager ObjectModelerSystem CATPLMIntegrationUse PLMDictionaryNavServices CATPLMIdentificationAccess DI0PANV2 JS0FM KnowledgeItf CATObjectModelerBase CATPLMComponentInterfaces CATPLMIntegrationAccess PLMSetupDataInterfaces PLMLibraryNavUseItf CATCfgUseItf CATPLMCfgUXItf CatXmlItfBase CatXmlItfExt
MOD_Included=M_CUS_UtilFunc
M_CatXmlItfExt=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\XMLParserItf\CatXmlItfExt.m" CatXmlItfExt - - - - - -
M_CATPLMIdentificationAccess=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIdentificationAccess\CATPLMIdentificationAccess.m" CATPLMIdentificationAccess - - - - - -
M_CATSysTS=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysTS.m" CATSysTS - - - - - -
FWPATH=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService
MK_BUILD_CONFIGURATION=
MKMK_DEBUG=YES
M_CATPLMIntegrationAccess=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMIntegrationAccess\CATPLMIntegrationAccess.m" CATPLMIntegrationAccess - - - - - -
M_CATPLMCfgUXItf=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\CATPLMConfigUXItf\CATPLMCfgUXItf.m" CATPLMCfgUXItf - - - - - -
FWSOURCES=C:\Works\DS\COMAC_DEL2\.\CM_UnitityService
STEPS_TO_CLEAN=
M_CATSysMultiThreading=mkSharedLibrary "C:\Program Files\Dassault Systemes\B422\.\SystemTS\CATSysMultiThreading.m" CATSysMultiThreading - - - - - -
MKMK_DEBUGEDITANDCONTINUE=
FWDNAME=CM_UnitityService
MODNAME=CUS_UtilFunc
REAL_LINK_WITH=JS0GROUP JS0BASEILB CATSysMultiThreading CATSysTS CATSysTSObjectModeler CATAfrFoundation CATAfrItf CATVisItf CATAfrCompanion CATAfrComponentsModel SceneGraphManager CATOmx ObjectModelerSystem CATPLMIntegrationUse PLMDictionaryNavServices CATPLMIdentificationAccess DI0PANV2 JS0FM KnowledgeItf CATObjectModelerBase CATProviderItf CATPLMComponentInterfaces CATPLMIntegrationAccess PLMSetupDataInterfaces PLMLibraryNavUseItf CATCfgUseItf CATPLMCfgUXItf CatXmlItfBase CatXmlItfExt
