//===================================================================
// COPYRIGHT DS 2021/11/30
//===================================================================
// CAAUtilityMdl.cpp
// Header definition of class CAAUtilityMdl
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/11/30 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByCAAUtilityMdl_H
#define ExportedByCAAUtilityMdl_H
#if defined(__CAAUtilityMdl)
# define ExportedByCAAUtilityMdl   DSYExport
#else // __CAAUtilityMdl
# define ExportedByCAAUtilityMdl   DSYImport
#endif  // __CAAUtilityMdl
#include "DSYExport.h"
#endif //ExportedByCAAUtilityMdl_H

