//===================================================================
// COPYRIGHT DS 2021/12/06
//===================================================================
// COMACWIAddin.cpp
// Header definition of class COMACWIAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/12/06 Creation: Code generated by the 3DS wizard
//===================================================================

#include "COMACWIAddin.h"

CATImplementClass(COMACWIAddin,Implementation,CATBaseUnknown,CATNull);

#include "TIE_IDELWIWkbAddin.h"
TIE_IDELWIWkbAddin(COMACWIAddin);

//AfrFoundation 
#include "CATAfrCommandHeader.h"
#include "CATCreateWorkshop.h"
//-----------------------------------------------------------------------------
// COMACWIAddin : constructor
//-----------------------------------------------------------------------------
COMACWIAddin::COMACWIAddin():CATBaseUnknown()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// COMACWIAddin : destructor
//-----------------------------------------------------------------------------
COMACWIAddin::~COMACWIAddin()
{
//
// TODO: Place code here.
//
}

void COMACWIAddin::CreateCommands()
{

	CATAfrCommandHeader::CATCreateCommandHeader("ViewToPic", "COMACWIMdl",
		"COMACView2PicCmd", (void *)NULL,
		"COMACWIAddinHeader", CATFrmAvailable);

}

CATCmdContainer * COMACWIAddin::CreateToolbars()
{
	NewAccess(CATCmdContainer, pMySection, WITool);
	NewAccess(CATCmdContainer, pMyContainer, MyToolbarAddin);
	SetAccessChild(pMySection, pMyContainer);

	NewAccess(CATCmdStarter, pViewToPic, ViewToPic);
	SetAccessCommand(pViewToPic, "ViewToPic");
	SetAccessChild(pMyContainer, pViewToPic);

	AddToolbarView(pMyContainer, -1, UnDock);

	return pMySection;

}







