//===================================================================
// COPYRIGHT DS 2021/11/30
//===================================================================
// COMACCommonAddin.cpp
// Header definition of class COMACCommonAddin
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2021/11/30 Creation: Code generated by the 3DS wizard
//===================================================================

#include "COMACCommonAddin.h"

CATImplementClass(COMACCommonAddin,Implementation,CATBaseUnknown,CATNull);

#include "TIE_CATIAfrGeneralWksAddin.h"
TIE_CATIAfrGeneralWksAddin(COMACCommonAddin);

//AfrFoundation 
#include "CATAfrCommandHeader.h"
#include "CATCreateWorkshop.h"
//-----------------------------------------------------------------------------
// COMACCommonAddin : constructor
//-----------------------------------------------------------------------------
COMACCommonAddin::COMACCommonAddin():CATBaseUnknown()
{
//
//TODO: Add the constructor code here
//
}

//-----------------------------------------------------------------------------
// COMACCommonAddin : destructor
//-----------------------------------------------------------------------------
COMACCommonAddin::~COMACCommonAddin()
{
//
// TODO: Place code here.
//
}

void COMACCommonAddin::CreateCommands()
{

	CATAfrCommandHeader::CATCreateCommandHeader("MBOMInit", 
												"COMACCommonMdl",
												"COMACMBOMInitCmd", 
												(void *)NULL,
												"COMACCommonAddinHeader",
												CATFrmAvailable);

	// 协作BOM 规划  ComacGenerateBOM
	CATAfrCommandHeader::CATCreateCommandHeader("ComacGenerateBOMHdr",
												"COMACCommonMdl",
												"ComacGenerateBOMCmd",
												(void  *)NULL,
												"COMACCommonAddinHeader",
												CATFrmAvailable);

	// 指定插入FO、instruction  ComacInsertFOinstruction
	CATAfrCommandHeader::CATCreateCommandHeader("ComacInsertFOinstructionHdr",
												"COMACCommonMdl",
												"ComacInsertFOinstructionCmd",
												(void  *)NULL,
												"COMACCommonAddinHeader",
												CATFrmAvailable);
	//// 调用 排序 PLMReorder
	//CATAfrCommandHeader::CATCreateCommandHeader("COMACPLMReorderHdr",
	//											"COMACCommonMdl",
	//											"COMACPLMReorderCmd",
	//											(void  *)NULL,
	//											"COMACCommonAddinHeader",
	//											CATFrmAvailable);

	// 重命名Operations  ComacReNameOperationsCmd
	CATAfrCommandHeader::CATCreateCommandHeader("ComacReNameOperationsHdr",
												"COMACCommonMdl",
												"ComacReNameOperationsCmd",
												(void  *)NULL,
												"COMACCommonAddinHeader",
												CATFrmAvailable);

	// 升版 动作 放在 “接收FP任务”功能里！
	// 升版  ComacNewVersionCmd    icon: I_MajorVersion  ootb Hdr: NewVersion  current Hdr:ComacNewVersionHdr
	CATAfrCommandHeader::CATCreateCommandHeader("ComacNewVersionHdr",
												"COMACCommonMdl",
												"ComacNewVersionCmd",
												(void  *)NULL,
												"COMACCommonAddinHeader",
												CATFrmAvailable);

}

CATCmdContainer * COMACCommonAddin::CreateToolbars()
{
	NewAccess(CATCmdContainer, pMySection, MBOM);
	NewAccess(CATCmdContainer, pMyContainer, MyToolbarAddin);
	SetAccessChild(pMySection, pMyContainer);

	NewAccess(CATCmdStarter, pMBOMInit, MBOMInit);
	SetAccessCommand(pMBOMInit, "MBOMInit");
	SetAccessChild(pMyContainer, pMBOMInit);

	// 协作BOM 规划  ComacGenerateBOM
	NewAccess(CATCmdStarter, pComacGenerateBOM, ComacGenerateBOM);
	SetAccessCommand(pComacGenerateBOM, "ComacGenerateBOMHdr");
	SetAccessNext(pMBOMInit, pComacGenerateBOM);

	// 指定插入FO、instruction  ComacInsertFOinstruction
	NewAccess(CATCmdStarter, pComacInsertFOinstruction, ComacInsertFOinstruction);
	SetAccessCommand(pComacInsertFOinstruction, "ComacInsertFOinstructionHdr");
	SetAccessNext(pComacGenerateBOM, pComacInsertFOinstruction);

	//// 调用 排序 PLMReorder
	//NewAccess(CATCmdStarter, pCOMACPLMReorder, COMACPLMReorder);
	//SetAccessCommand(pCOMACPLMReorder, "COMACPLMReorderHdr");
	//SetAccessNext(pComacInsertFOinstruction, pCOMACPLMReorder);

	// 重命名Operations  ComacReNameOperationsCmd
	NewAccess(CATCmdStarter, pComacReNameOperations, ComacReNameOperations);
	SetAccessCommand(pComacReNameOperations, "ComacReNameOperationsHdr");
	SetAccessNext(pComacInsertFOinstruction, pComacReNameOperations);

	
	// 升版  ComacNewVersionCmd    icon: I_MajorVersion  ootb Hdr: NewVersion  current Hdr:ComacNewVersionHdr
	NewAccess(CATCmdStarter, pComacNewVersion, ComacNewVersion);
	SetAccessCommand(pComacNewVersion, "ComacNewVersionHdr");
	SetAccessNext(pComacReNameOperations, pComacNewVersion);



	AddToolbarView(pMyContainer, -1, UnDock);

	return pMySection;

}







